# Generated by Django 5.2.8 on 2026-01-30 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('COLECCION', 'Colección'), ('OBRA_SUELTA', 'Obra suelta')], default='COLECCION', max_length=20)),
                ('estado', models.CharField(choices=[('NUEVO', 'Nuevo'), ('IMPORTADO', 'Importado'), ('SEGMENTADO', 'Segmentado')], default='NUEVO', max_length=20)),
                ('total_pages', models.PositiveIntegerField(default=0)),
                ('inbox_path', models.CharField(blank=True, default='', max_length=500)),
                ('repository_path', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pdf_path', models.CharField(blank=True, default='', max_length=700)),
                ('pdf_total_pages', models.PositiveIntegerField(default=0)),
                ('pdf_thumb_path', models.CharField(blank=True, default='', max_length=700)),
                ('obra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digital_set', to='catalogacion.obrageneral')),
            ],
        ),
        migrations.CreateModel(
            name='WorkSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_page', models.PositiveIntegerField()),
                ('end_page', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('OBRA', 'Obra'), ('NOTAS', 'Notas'), ('ANEXO', 'Anexo'), ('EXCLUIDO', 'Excluido')], default='OBRA', max_length=20)),
                ('cached_pdf_path', models.CharField(blank=True, default='', max_length=700)),
                ('cached_pdf_generated_at', models.DateTimeField(blank=True, null=True)),
                ('cached_thumb_path', models.CharField(blank=True, default='', max_length=700)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('digital_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='digitalizacion.digitalset')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='catalogacion.obrageneral')),
            ],
            options={
                'ordering': ['start_page', 'end_page'],
            },
        ),
        migrations.CreateModel(
            name='DigitalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('source_path', models.CharField(blank=True, default='', max_length=700)),
                ('master_path', models.CharField(blank=True, default='', max_length=700)),
                ('derivative_path', models.CharField(blank=True, default='', max_length=700)),
                ('digital_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='digitalizacion.digitalset')),
            ],
            options={
                'ordering': ['page_number'],
                'unique_together': {('digital_set', 'page_number')},
            },
        ),
    ]
