# Generated by Django 5.2.8 on 2026-01-10 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('NEW', 'Nuevo'), ('IMPORTED', 'Importado'), ('SEGMENTED', 'Segmentado')], default='NEW', max_length=20)),
                ('total_pages', models.PositiveIntegerField(default=0)),
                ('inbox_path', models.CharField(blank=True, default='', max_length=500)),
                ('repository_path', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coleccion', models.OneToOneField(limit_choices_to={'nivel_bibliografico': 'c'}, on_delete=django.db.models.deletion.CASCADE, related_name='digital_set', to='catalogacion.obrageneral')),
            ],
        ),
        migrations.CreateModel(
            name='DigitalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('master_path', models.CharField(max_length=700)),
                ('derivative_path', models.CharField(blank=True, default='', max_length=700)),
                ('digital_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='digitalizacion.digitalset')),
            ],
            options={
                'ordering': ['page_number'],
                'unique_together': {('digital_set', 'page_number')},
            },
        ),
    ]
