# Generated by Django 5.2.8 on 2026-01-10 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0001_initial'),
        ('digitalizacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_page', models.PositiveIntegerField()),
                ('end_page', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('OBRA', 'Obra'), ('NOTAS', 'Notas'), ('ANEXO', 'Anexo'), ('EXCLUIDO', 'Excluido')], default='OBRA', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('digital_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='digitalizacion.digitalset')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='catalogacion.obrageneral')),
            ],
            options={
                'ordering': ['start_page', 'end_page'],
            },
        ),
    ]
