# Generated by Django 5.2.8 on 2026-01-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalizacion', '0002_worksegment'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalset',
            name='pdf_path',
            field=models.CharField(blank=True, default='', max_length=700),
        ),
    ]
