# Generated by Django 5.2.8 on 2026-01-18 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalizacion', '0003_digitalset_pdf_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalset',
            name='pdf_total_pages',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
