# Generated by Django 5.2.8 on 2026-01-27 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0002_borradorobra_usuario_obrageneral_catalogador_and_more'),
        ('digitalizacion', '0006_generalizar_digitalset'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalpage',
            name='source_path',
            field=models.CharField(blank=True, default='', max_length=700),
        ),
        migrations.AddField(
            model_name='worksegment',
            name='cached_pdf_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worksegment',
            name='cached_pdf_path',
            field=models.CharField(blank=True, default='', max_length=700),
        ),
        migrations.AlterField(
            model_name='digitalpage',
            name='master_path',
            field=models.CharField(blank=True, default='', max_length=700),
        ),
        migrations.AlterField(
            model_name='digitalset',
            name='obra',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digital_set', to='catalogacion.obrageneral'),
        ),
    ]
