# Generated by Django 5.2.8 on 2026-01-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalizacion', '0007_add_segment_pdf_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalset',
            name='pdf_thumb_path',
            field=models.CharField(blank=True, default='', max_length=700),
        ),
        migrations.AddField(
            model_name='worksegment',
            name='cached_thumb_path',
            field=models.CharField(blank=True, default='', max_length=700),
        ),
    ]
