# Generated by Django 5.2.8 on 2026-01-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tipo_catalogador',
            field=models.CharField(blank=True, choices=[('investigador_unl', 'Investigador UNL'), ('investigador_externo', 'Investigador Externo'), ('colaborador', 'Colaborador'), ('pasante', 'Pasante'), ('otros', 'Otros')], default='investigador_unl', help_text='Clasificación del catalogador según su rol en la institución', max_length=30, verbose_name='Tipo de Catalogador'),
        ),
    ]
