# Generated by Django 5.1.2 on 2026-02-24 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tipo_catalogador',
            field=models.CharField(choices=[('investigador_unl', 'Investigador UNL'), ('investigador_externo', 'Investigador Externo'), ('colaborador', 'Colaborador'), ('pasante', 'Pasante'), ('otros', 'Otros')], default='otros', help_text='Clasificación del catalogador según su rol en la institución', max_length=30, verbose_name='Tipo de Catalogador'),
        ),
        migrations.CreateModel(
            name='SolicitudUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=250, verbose_name='Nombres completos')),
                ('cedula', models.CharField(max_length=50, verbose_name='Cédula')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo')),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('tipo_usuario', models.CharField(choices=[('Catalogador', 'Catalogador'), ('Administrador', 'Administrador'), ('Consulta', 'Consulta'), ('Otro', 'Otro')], max_length=30, verbose_name='Tipo solicitado')),
                ('motivo', models.TextField(help_text='Razón para solicitar acceso', verbose_name='Motivo')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de respuesta')),
                ('respondido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_respondidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Cuenta',
                'verbose_name_plural': 'Solicitudes de Cuenta',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=300)),
                ('leido', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='usuarios.solicitudusuario')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='solicitudusuario',
            index=models.Index(fields=['correo'], name='usuarios_so_correo_48e1b7_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudusuario',
            index=models.Index(fields=['cedula'], name='usuarios_so_cedula_5b87cc_idx'),
        ),
    ]
