# Generated by Django 5.2.7 on 2025-12-03 23:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el usuario puede acceder al sistema', verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='nombre_completo',
            field=models.CharField(blank=True, help_text='Nombre completo del usuario', max_length=200, verbose_name='Nombre completo'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('catalogador', 'Catalogador'), ('admin', 'Administrador')], default='catalogador', help_text='Define los permisos del usuario en el sistema', max_length=20, verbose_name='Rol'),
        ),
    ]
