# Generated by Django 5.2.8 on 2026-01-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_customuser_tipo_catalogador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tipo_catalogador',
            field=models.CharField(choices=[('investigador_unl', 'Investigador UNL'), ('investigador_externo', 'Investigador Externo'), ('colaborador', 'Colaborador'), ('pasante', 'Pasante'), ('otros', 'Otros')], default='otros', help_text='Clasificación del catalogador según su rol en la institución', max_length=30, verbose_name='Tipo de Catalogador'),
        ),
    ]
