# Generated by Django 5.2.7 on 2025-11-13 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoridadEntidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300, unique=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Autoridad de entidad',
                'verbose_name_plural': 'Autoridades de entidades',
            },
        ),
        migrations.CreateModel(
            name='AutoridadFormaMusical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma', models.CharField(help_text='Forma o género musical (ej: Pasillo, Sinfonía, Vals)', max_length=100, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Autoridad - Forma Musical',
                'verbose_name_plural': 'Autoridades - Formas Musicales',
                'ordering': ['forma'],
            },
        ),
        migrations.CreateModel(
            name='AutoridadMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termino', models.CharField(help_text='Término de materia normalizado', max_length=200, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Autoridad - Materia',
                'verbose_name_plural': 'Autoridades - Materias',
                'ordering': ['termino'],
            },
        ),
        migrations.CreateModel(
            name='AutoridadPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellidos_nombres', models.CharField(help_text='Formato: Apellidos, Nombres (normalizado)', max_length=200, unique=True)),
                ('fechas', models.CharField(blank=True, help_text='Coordenadas biográficas: año nacimiento - año muerte', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Autoridad - Persona',
                'verbose_name_plural': 'Autoridades - Personas',
                'ordering': ['apellidos_nombres'],
            },
        ),
        migrations.CreateModel(
            name='AutoridadTituloUniforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título uniforme normalizado', max_length=300, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Autoridad - Título Uniforme',
                'verbose_name_plural': 'Autoridades - Títulos Uniformes',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='CodigoLengua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicacion_traduccion', models.CharField(choices=[('#', 'No se proporciona información'), ('0', 'El documento no es ni incluye una traducción'), ('1', 'El documento es o incluye una traducción')], default='0', help_text='Primer indicador: ¿Es traducción?', max_length=1)),
                ('fuente_codigo', models.CharField(choices=[('#', 'Código MARC de lengua'), ('7', 'Fuente especificada en el subcampo $2')], default='#', help_text='Segundo indicador: Fuente del código', max_length=1)),
                ('fuente_especificada', models.CharField(blank=True, help_text='041 $2 – Fuente del código (solo si segundo indicador es 7)', max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Código de Lengua (041)',
                'verbose_name_plural': 'Códigos de Lengua (041 - R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DescripcionFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otras_caracteristicas_fisicas', models.CharField(blank=True, help_text='300 $b – Otras características físicas (NR)', max_length=300, null=True)),
                ('material_acompanante', models.CharField(blank=True, help_text='300 $e – Material acompañante (NR)', max_length=300, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Descripción Física (300)',
                'verbose_name_plural': 'Descripciones Físicas (300 - R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DesignacionNumericaObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Designación Numérica (383)',
                'verbose_name_plural': 'Designaciones Numéricas (383 - R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IncipitMusical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_obra', models.PositiveIntegerField(default=1, help_text='031 $a – Número de la obra (predeterminado: 1)')),
                ('numero_movimiento', models.PositiveIntegerField(default=1, help_text='031 $b – Número del movimiento (predeterminado: 1)')),
                ('numero_pasaje', models.PositiveIntegerField(default=1, help_text='031 $c – Número de pasaje o sistema (predeterminado: 1)')),
                ('titulo_encabezamiento', models.CharField(blank=True, help_text='031 $d – Nombre del tempo o movimiento (ej: Aria, Allegro, Andante)', max_length=200, null=True)),
                ('voz_instrumento', models.CharField(blank=True, default='piano', help_text='031 $m – Voz/instrumento', max_length=100, null=True)),
                ('notacion_musical', models.TextField(blank=True, help_text='031 $p – Íncipit musical codificado (ej: Plaine & Easie, MusicXML, ABC)', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Íncipit Musical (031)',
                'verbose_name_plural': 'Íncipits Musicales (031 - R)',
                'ordering': ['obra', 'numero_obra', 'numero_movimiento', 'numero_pasaje'],
            },
        ),
        migrations.CreateModel(
            name='MedioInterpretacion382',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Medio de Interpretación (382)',
                'verbose_name_plural': 'Medios de Interpretación (382 - R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Dimension300',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(help_text="300 $c – Dimensión (ej: '30 cm', '2.5 MB')", max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('descripcion_fisica', models.ForeignKey(help_text='Descripción física a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='dimensiones_set', to='catalogacion.descripcionfisica')),
            ],
            options={
                'verbose_name': 'Dimensión (300 $c)',
                'verbose_name_plural': 'Dimensiones (300 $c - R)',
                'ordering': ['descripcion_fisica', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Extension300',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(help_text="300 $a – Extensión (ej: '1 partitura (24 p.)')", max_length=500)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('descripcion_fisica', models.ForeignKey(help_text='Descripción física a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='extensiones', to='catalogacion.descripcionfisica')),
            ],
            options={
                'verbose_name': 'Extensión (300 $a)',
                'verbose_name_plural': 'Extensiones (300 $a - R)',
                'ordering': ['descripcion_fisica', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IdiomaObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_idioma', models.CharField(choices=[('ger', 'Alemán'), ('spa', 'Español'), ('fre', 'Francés'), ('eng', 'Inglés'), ('ita', 'Italiano'), ('por', 'Portugués')], default='spa', help_text='041 $a – Código ISO 639-2/B del idioma', max_length=3)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('codigo_lengua', models.ForeignKey(help_text='Registro 041 al que pertenece este idioma', on_delete=django.db.models.deletion.CASCADE, related_name='idiomas', to='catalogacion.codigolengua')),
            ],
            options={
                'verbose_name': 'Idioma (041 $a)',
                'verbose_name_plural': 'Idiomas (041 $a - R)',
                'ordering': ['codigo_lengua', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IncipitURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='031 $u – URL del íncipit codificado en base de datos externa', max_length=500)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('incipit', models.ForeignKey(help_text='Íncipit al que pertenece esta URL', on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='catalogacion.incipitmusical')),
            ],
            options={
                'verbose_name': 'URL de Íncipit (031 $u)',
                'verbose_name_plural': 'URLs de Íncipit (031 $u - R)',
                'ordering': ['incipit', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MedioInterpretacion382_a',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medio', models.CharField(choices=[('piano', 'Piano'), ('dos pianos', 'Dos pianos'), ('piano a cuatro manos', 'Piano a cuatro manos'), ('piano con acompañamiento', 'Piano con acompañamiento')], default='piano', help_text='382 $a – Medio de interpretación (predeterminado: piano)', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('medio_interpretacion', models.ForeignKey(help_text='Medio de interpretación al que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='medios', to='catalogacion.mediointerpretacion382')),
            ],
            options={
                'verbose_name': 'Medio (382 $a)',
                'verbose_name_plural': 'Medios (382 $a - R)',
                'ordering': ['medio_interpretacion', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NombreRelacionado700',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechas', models.CharField(blank=True, help_text='700 $d – Fechas asociadas al nombre (NR)', max_length=50, null=True)),
                ('titulo_obra', models.CharField(blank=True, help_text='700 $t – Título de la obra (NR)', max_length=250, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('persona', models.ForeignKey(help_text='700 $a – Apellidos, Nombres (controlado, NR)', on_delete=django.db.models.deletion.PROTECT, to='catalogacion.autoridadpersona')),
            ],
            options={
                'verbose_name': '700 – Nombre relacionado',
                'verbose_name_plural': '700 – Nombres relacionados (R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Funcion700',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcion', models.CharField(choices=[('arreglista', 'Arreglista'), ('coeditor', 'Coeditor'), ('compilador', 'Compilador'), ('compositor', 'Compositor'), ('copista', 'Copista'), ('dedicatario', 'Dedicatorio'), ('editor', 'Editor'), ('prologuista', 'Prologuista')], help_text='700 $e – Función (R)', max_length=30)),
                ('nombre_700', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funciones', to='catalogacion.nombrerelacionado700')),
            ],
            options={
                'verbose_name': '700 $e – Función',
                'verbose_name_plural': '700 $e – Funciones (R)',
                'ordering': ['nombre_700', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Autoria700',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autoria', models.CharField(choices=[('atribuida', 'Atribuida'), ('certificada', 'Certificada'), ('erronea', 'Errónea')], default='certificada', help_text='700 $j – Autoría (R)', max_length=20)),
                ('nombre_700', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autoridades_autoria', to='catalogacion.nombrerelacionado700')),
            ],
            options={
                'verbose_name': '700 $j – Autoría',
                'verbose_name_plural': '700 $j – Autorías (R)',
                'ordering': ['nombre_700', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NumeroInterpretes382',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text='382 $n – Número de intérpretes de un mismo medio (ej: 2, 4, 8)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('medio_interpretacion', models.ForeignKey(help_text='Medio de interpretación al que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='numeros_interpretes', to='catalogacion.mediointerpretacion382')),
            ],
            options={
                'verbose_name': 'Número Intérpretes (382 $n)',
                'verbose_name_plural': 'Números Intérpretes (382 $n - R)',
                'ordering': ['medio_interpretacion', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NumeroObra383',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_obra', models.CharField(help_text="383 $a – Número de obra (ej: '1', '2', 'K. 545', 'BWV 1001')", max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('designacion_numerica', models.ForeignKey(help_text='Designación a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='numeros_obra', to='catalogacion.designacionnumericaobra')),
            ],
            options={
                'verbose_name': 'Número de Obra (383 $a)',
                'verbose_name_plural': 'Números de Obra (383 $a - R)',
                'ordering': ['designacion_numerica', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ObraGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_registro', models.CharField(default='n', editable=False, help_text='Posición 05: Estado del registro (n=nuevo)', max_length=1)),
                ('tipo_registro', models.CharField(choices=[('c', 'Música impresa'), ('d', 'Música manuscrita')], default='d', help_text='Posición 06: Tipo de registro', max_length=1)),
                ('nivel_bibliografico', models.CharField(choices=[('a', 'Parte componente'), ('c', 'Colección'), ('m', 'Obra independiente')], default='m', help_text='Posición 07: Nivel bibliográfico', max_length=1)),
                ('num_control', models.CharField(editable=False, help_text='001 - Número de control (6 dígitos)', max_length=6, unique=True)),
                ('fecha_hora_ultima_transaccion', models.CharField(editable=False, help_text='005 - Fecha y hora de última modificación', max_length=14)),
                ('codigo_informacion', models.CharField(editable=False, help_text='008 - Información codificada', max_length=40)),
                ('isbn', models.CharField(blank=True, help_text='020 $a – ISBN (NR - No Repetible)', max_length=20, null=True)),
                ('ismn', models.CharField(blank=True, help_text='024 $a – ISMN (NR - No Repetible)', max_length=20, null=True)),
                ('numero_editor', models.CharField(blank=True, help_text='028 $a – Número de editor, plancha o placa (NR - No Repetible)', max_length=100, null=True)),
                ('nombre_editor', models.CharField(blank=True, help_text='028 $b – Nombre del editor (NR - No Repetible)', max_length=200, null=True)),
                ('centro_catalogador', models.CharField(default='UNL', help_text='040 $a – Centro catalogador (predeterminado: UNL)', max_length=10)),
                ('clasif_institucion', models.CharField(default='UNL', editable=False, help_text='092 $a – Institución (duplica campo 040 $a)', max_length=10)),
                ('clasif_proyecto', models.CharField(default='BLMP', editable=False, help_text='092 $b – Proyecto', max_length=50)),
                ('clasif_pais', models.CharField(blank=True, editable=False, help_text='092 $c – País (duplica campo 044 $a)', max_length=10, null=True)),
                ('clasif_ms_imp', models.CharField(blank=True, choices=[('Ms', 'Manuscrito'), ('Imp', 'Impreso')], editable=False, help_text='092 $d – Ms (Manuscrito) o Imp (Impreso) - Cruza con posición 06 de cabecera', max_length=3, null=True)),
                ('clasif_num_control', models.CharField(blank=True, editable=False, help_text='092 $0 – Número de control (duplica campo 001)', max_length=50, null=True)),
                ('atribucion_compositor', models.CharField(blank=True, choices=[('atribuido', 'Atribuido'), ('dudoso', 'Dudoso')], help_text='100 $j – Atribución del compositor (NR - No Repetible)', max_length=50, null=True)),
                ('medio_interpretacion_130', models.CharField(blank=True, help_text='130 $m – Medio de interpretación (NR - No Repetible)', max_length=200, null=True)),
                ('numero_parte_130', models.CharField(blank=True, help_text='130 $n – Número de parte/sección (NR - No Repetible)', max_length=100, null=True)),
                ('nombre_parte_130', models.CharField(blank=True, help_text='130 $p – Nombre de parte/sección (NR - No Repetible)', max_length=300, null=True)),
                ('titulo_uniforme_arreglo', models.CharField(blank=True, default='arreglo', help_text='130 $o – Arreglo (NR - No Repetible)', max_length=10, null=True)),
                ('titulo_uniforme_tonalidad', models.CharField(blank=True, choices=[('Do mayor', 'Do mayor'), ('Do# mayor', 'Do# mayor'), ('Reb mayor', 'Re♭ mayor'), ('Re mayor', 'Re mayor'), ('Mib mayor', 'Mi♭ mayor'), ('Mi mayor', 'Mi mayor'), ('Fa mayor', 'Fa mayor'), ('Fa# mayor', 'Fa# mayor'), ('Sol mayor', 'Sol mayor'), ('Sol# mayor', 'Sol# mayor'), ('Lab mayor', 'La♭ mayor'), ('La mayor', 'La mayor'), ('Sib mayor', 'Si♭ mayor'), ('Si mayor', 'Si mayor'), ('Do menor', 'Do menor'), ('Do# menor', 'Do# menor'), ('Reb menor', 'Re♭ menor'), ('Re menor', 'Re menor'), ('Mib menor', 'Mi♭ menor'), ('Mi menor', 'Mi menor'), ('Fa menor', 'Fa menor'), ('Fa# menor', 'Fa# menor'), ('Sol menor', 'Sol menor'), ('Sol# menor', 'Sol# menor'), ('Lab menor', 'La♭ menor'), ('La menor', 'La menor'), ('Sib menor', 'Si♭ menor'), ('Si menor', 'Si menor')], help_text='130 $r – Tonalidad (NR - No repetible)', max_length=20, null=True)),
                ('medio_interpretacion_240', models.CharField(blank=True, help_text='240 $m – Medio de interpretación (NR - No Repetible)', max_length=200, null=True)),
                ('numero_parte_240', models.CharField(blank=True, help_text='240 $n – Número de parte/sección (NR - No Repetible)', max_length=100, null=True)),
                ('nombre_parte_240', models.CharField(blank=True, help_text='240 $p – Nombre de parte/sección (NR - No Repetible)', max_length=300, null=True)),
                ('titulo_240_arreglo', models.CharField(blank=True, default='arreglo', help_text='240 $o – Arreglo (NR - No Repetible)', max_length=10, null=True)),
                ('titulo_240_tonalidad', models.CharField(blank=True, choices=[('Do mayor', 'Do mayor'), ('Do# mayor', 'Do# mayor'), ('Reb mayor', 'Re♭ mayor'), ('Re mayor', 'Re mayor'), ('Mib mayor', 'Mi♭ mayor'), ('Mi mayor', 'Mi mayor'), ('Fa mayor', 'Fa mayor'), ('Fa# mayor', 'Fa# mayor'), ('Sol mayor', 'Sol mayor'), ('Sol# mayor', 'Sol# mayor'), ('Lab mayor', 'La♭ mayor'), ('La mayor', 'La mayor'), ('Sib mayor', 'Si♭ mayor'), ('Si mayor', 'Si mayor'), ('Do menor', 'Do menor'), ('Do# menor', 'Do# menor'), ('Reb menor', 'Re♭ menor'), ('Re menor', 'Re menor'), ('Mib menor', 'Mi♭ menor'), ('Mi menor', 'Mi menor'), ('Fa menor', 'Fa menor'), ('Fa# menor', 'Fa# menor'), ('Sol menor', 'Sol menor'), ('Sol# menor', 'Sol# menor'), ('Lab menor', 'La♭ menor'), ('La menor', 'La menor'), ('Sib menor', 'Si♭ menor'), ('Si menor', 'Si menor')], help_text='240 $r – Tonalidad (NR - No repetible)', max_length=20, null=True)),
                ('titulo_principal', models.CharField(blank=True, help_text='245 $a – Título principal', max_length=500, null=True)),
                ('subtitulo', models.CharField(blank=True, help_text='245 $b – Subtítulo', max_length=500, null=True)),
                ('mencion_responsabilidad', models.TextField(blank=True, help_text='245 $c – Mención de responsabilidad', null=True)),
                ('extension_300a', models.CharField(blank=True, help_text='300 $a – Extensión (NR - No Repetible)', max_length=300, null=True)),
                ('otras_caracteristicas_300b', models.CharField(blank=True, help_text='300 $b – Otras características físicas (NR - No Repetible)', max_length=300, null=True)),
                ('dimension_300c', models.CharField(blank=True, help_text='300 $c – Dimensión (NR - No Repetible)', max_length=100, null=True)),
                ('material_acompanante_300e', models.CharField(blank=True, help_text='300 $e – Material acompañante (NR - No Repetible)', max_length=300, null=True)),
                ('tecnica_340d', models.CharField(blank=True, help_text='340 $d – Técnica (NR - No Repetible)', max_length=200, null=True)),
                ('formato_348a', models.CharField(blank=True, help_text='348 $a – Formato de la música notada (NR - No Repetible)', max_length=100, null=True)),
                ('solista_382b', models.CharField(blank=True, help_text='382 $b – Solista (NR - No Repetible)', max_length=200, null=True)),
                ('numero_obra_383a', models.CharField(blank=True, help_text='383 $a – Número serial de obra musical (NR - No Repetible)', max_length=100, null=True)),
                ('opus_383b', models.CharField(blank=True, help_text='383 $b – Número de opus (NR - No Repetible)', max_length=100, null=True)),
                ('tonalidad_384', models.CharField(blank=True, choices=[('Do mayor', 'Do mayor'), ('Do# mayor', 'Do# mayor'), ('Reb mayor', 'Re♭ mayor'), ('Re mayor', 'Re mayor'), ('Mib mayor', 'Mi♭ mayor'), ('Mi mayor', 'Mi mayor'), ('Fa mayor', 'Fa mayor'), ('Fa# mayor', 'Fa# mayor'), ('Sol mayor', 'Sol mayor'), ('Sol# mayor', 'Sol# mayor'), ('Lab mayor', 'La♭ mayor'), ('La mayor', 'La mayor'), ('Sib mayor', 'Si♭ mayor'), ('Si mayor', 'Si mayor'), ('Do menor', 'Do menor'), ('Do# menor', 'Do# menor'), ('Reb menor', 'Re♭ menor'), ('Re menor', 'Re menor'), ('Mib menor', 'Mi♭ menor'), ('Mi menor', 'Mi menor'), ('Fa menor', 'Fa menor'), ('Fa# menor', 'Fa# menor'), ('Sol menor', 'Sol menor'), ('Sol# menor', 'Sol# menor'), ('Lab menor', 'La♭ menor'), ('La menor', 'La menor'), ('Sib menor', 'Si♭ menor'), ('Si menor', 'Si menor')], help_text='384 $a – Tonalidad (NR - No Repetible)', max_length=20, null=True)),
                ('sumario_520', models.TextField(blank=True, help_text='520 ## $a Sumario (NR)', max_length=2000, null=True)),
                ('materia_principal_650', models.CharField(blank=True, help_text='650 $a – Materia (Tema principal) (NR)', max_length=200, null=True)),
                ('materia_genero_655', models.CharField(blank=True, help_text='655 $a – Materia (Género/Forma) (NR)', max_length=200, null=True)),
                ('coordenadas_biograficas_700d', models.CharField(blank=True, help_text='700 $d – Coordenadas biográficas (NR)', max_length=200, null=True)),
                ('titulo_relacionado_700t', models.CharField(blank=True, help_text='700 $t – Título de la obra relacionada (NR)', max_length=250, null=True)),
                ('titulo_coleccion_773t', models.CharField(blank=True, help_text='773 $t – Título de la colección (NR)', max_length=250, null=True)),
                ('enlace_unidad_774', models.URLField(blank=True, help_text='774 $a – Enlace a la unidad constituyente (NR)', null=True)),
                ('titulo_unidad_774t', models.CharField(blank=True, help_text='774 $t – Título de la unidad constituyente (NR)', max_length=250, null=True)),
                ('encabezamiento_principal_787a', models.CharField(blank=True, help_text='787 $a – Encabezamiento principal (NR)', max_length=250, null=True)),
                ('titulo_obra_relacionada_787t', models.CharField(blank=True, help_text='787 $t – Título de la obra relacionada (NR)', max_length=250, null=True)),
                ('signatura_original_852h', models.CharField(blank=True, help_text='852 $h – Signatura original (NR)', max_length=255, null=True)),
                ('fecha_creacion_sistema', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion_sistema', models.DateTimeField(auto_now=True)),
                ('compositor', models.ForeignKey(blank=True, help_text='100 $a y $d – Compositor principal (cruzar con 600, 700)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='obras_como_compositor', to='catalogacion.autoridadpersona')),
                ('compositor_coleccion_773a', models.ForeignKey(blank=True, help_text='773 $a – Compositor de la colección (NR)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='obras_coleccion_773a', to='catalogacion.autoridadpersona')),
                ('entidad_relacionada_710a', models.ForeignKey(blank=True, help_text='710 $a – Entidad o jurisdicción relacionada (NR)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='obras_relacionadas_710a', to='catalogacion.autoridadentidad')),
                ('forma_130', models.ForeignKey(blank=True, help_text='130 $k – Forma musical (NR - No Repetible)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='obras_forma_130', to='catalogacion.autoridadformamusical')),
                ('forma_240', models.ForeignKey(blank=True, help_text='240 $k – Forma musical (NR - No Repetible)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='obras_forma_240', to='catalogacion.autoridadformamusical')),
                ('institucion_persona_852a', models.ForeignKey(blank=True, help_text='852 $a – Institución o persona (NR). Enlace a autoridad institucional.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='obras_ubicacion_852a', to='catalogacion.autoridadentidad')),
                ('nombre_relacionado_700a', models.ForeignKey(blank=True, help_text='700 $a – Nombre personal relacionado (NR)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='obras_relacionadas_700a', to='catalogacion.autoridadpersona')),
                ('titulo_240', models.ForeignKey(blank=True, help_text='240 $a – Título uniforme normalizado (cruzar con campo 130)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='obras_240', to='catalogacion.autoridadtitulouniforme')),
                ('titulo_uniforme', models.ForeignKey(blank=True, help_text='130 $a – Título uniforme normalizado (cruzar con campo 240)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='obras_130', to='catalogacion.autoridadtitulouniforme')),
            ],
            options={
                'verbose_name': 'Obra Musical MARC21',
                'verbose_name_plural': 'Obras Musicales MARC21',
                'ordering': ['-num_control'],
            },
        ),
        migrations.CreateModel(
            name='NumeroParteSeccion240',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='240 $n – Número de parte/seccion (ej: I, II, III o 1, 2, 3)', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(help_text='Obra a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='numeros_parte_240', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': 'Número de Parte/Seccion (240 $n)',
                'verbose_name_plural': 'Números de Parte/Seccion (240 $n - R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NumeroParteSeccion130',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='130 $n – Número de parte/seccion (ej: I, II, III o 1, 2, 3)', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(help_text='Obra a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='numeros_parte_130', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': 'Número de Parte/Seccion (130 $n)',
                'verbose_name_plural': 'Números de Parte/Seccion (130 $n - R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NumeroEditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_editor', models.CharField(help_text='028 $a – Número de editor, plancha, placa o código distintivo', max_length=100)),
                ('tipo_numero', models.CharField(choices=[('0', 'Número de publicación'), ('1', 'Número de matriz'), ('2', 'Número de plancha'), ('3', 'Otro número de música'), ('4', 'Número de videograbación'), ('5', 'Otro número de editor')], default='2', help_text='Primer indicador: Tipo de número de editor', max_length=1)),
                ('control_nota', models.CharField(choices=[('0', 'No hay nota ni punto de acceso adicional'), ('1', 'Nota, hay punto de acceso adicional'), ('2', 'Nota, no hay punto de acceso adicional'), ('3', 'No hay nota, hay punto de acceso adicional')], default='0', help_text='Segundo indicador: Control de nota/punto de acceso adicional', max_length=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(help_text='Obra a la que pertenece este número de editor', on_delete=django.db.models.deletion.CASCADE, related_name='numeros_editor', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': 'Número de Editor (028)',
                'verbose_name_plural': 'Números de Editor (028 - R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NotaGeneral500',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_general', models.TextField(blank=True, help_text='500 $a – Nota general (R)', null=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_generales_500', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': '500 – Nota general',
                'verbose_name_plural': '500 – Notas generales (R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.AddField(
            model_name='nombrerelacionado700',
            name='obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nombres_relacionados_700', to='catalogacion.obrageneral'),
        ),
        migrations.CreateModel(
            name='NombreParteSeccion240',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='240 $p – Nombre de parte/seccion (ej: Allegro, Andante, Finale)', max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(help_text='Obra a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='nombres_parte_240', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': 'Nombre de Parte/Seccion (240 $p)',
                'verbose_name_plural': 'Nombres de Parte/Seccion (240 $p - R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NombreParteSeccion130',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='130 $p – Nombre de parte/seccion (ej: Allegro, Andante, Finale)', max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(help_text='Obra a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='nombres_parte_130', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': 'Nombre de Parte/Seccion (130 $p)',
                'verbose_name_plural': 'Nombres de Parte/Seccion (130 $p - R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MencionSerie490',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relacion', models.CharField(choices=[('0', 'No relacionado (sin entrada secundaria)'), ('1', 'Relacionado (con entrada secundaria 800-830)')], default='0', help_text='490 primer indicador – Relación: 0=no relacionado, 1=relacionado con 800-830', max_length=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(help_text='Obra a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='menciones_serie', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': 'Mención de Serie (490)',
                'verbose_name_plural': 'Menciones de Serie (490 - R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.AddField(
            model_name='mediointerpretacion382',
            name='obra',
            field=models.ForeignKey(help_text='Obra a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='medios_interpretacion_382', to='catalogacion.obrageneral'),
        ),
        migrations.CreateModel(
            name='MedioInterpretacion240',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medio', models.CharField(default='piano', help_text='240 $m – Medio de interpretacion (predeterminado: piano)', max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(help_text='Obra a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='medios_interpretacion_240', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': 'Medio de Interpretacion (240 $m)',
                'verbose_name_plural': 'Medios de Interpretacion (240 $m - R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MedioInterpretacion130',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medio', models.CharField(default='piano', help_text='130 $m – Medio de interpretacion (predeterminado: piano)', max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(help_text='Obra a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='medios_interpretacion_130', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': 'Medio de Interpretacion (130 $m)',
                'verbose_name_plural': 'Medios de Interpretacion (130 $m - R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MedioFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(help_text='Obra a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='medios_fisicos', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': 'Medio Físico (340)',
                'verbose_name_plural': 'Medios Físicos (340 - R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MateriaGenero655',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(help_text='655 $a – Materia (género/forma)', max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_655', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': '655 – Materia (Género/forma)',
                'verbose_name_plural': '655 – Materias (Género/forma)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Materia650',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(help_text='650 $a – Materia principal', max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_650', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': '650 – Materia (Tema)',
                'verbose_name_plural': '650 – Materias (Temas)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ISMN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismn', models.CharField(help_text='024 $a – ISMN', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(help_text='Obra a la que pertenece este ISMN', on_delete=django.db.models.deletion.CASCADE, related_name='ismns', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': 'ISMN (024)',
                'verbose_name_plural': 'ISMN (024)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ISBN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(help_text='020 $a – ISBN', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(help_text='Obra a la que pertenece este ISBN', on_delete=django.db.models.deletion.CASCADE, related_name='isbns', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': 'ISBN (020)',
                'verbose_name_plural': 'ISBN (020)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.AddField(
            model_name='incipitmusical',
            name='obra',
            field=models.ForeignKey(help_text='Obra a la que pertenece este íncipit', on_delete=django.db.models.deletion.CASCADE, related_name='incipits_musicales', to='catalogacion.obrageneral'),
        ),
        migrations.CreateModel(
            name='FuncionCompositor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcion', models.CharField(choices=[('arreglista', 'Arreglista'), ('coeditor', 'Coeditor'), ('compilador', 'Compilador'), ('compositor', 'Compositor'), ('copista', 'Copista'), ('dedicatario', 'Dedicatario'), ('editor', 'Editor'), ('prologuista', 'Prologuista')], default='compositor', help_text='100 $e – Funcion del compositor (predeterminado: compositor)', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(help_text='Obra a la que pertenece esta funcion', on_delete=django.db.models.deletion.CASCADE, related_name='funciones_compositor', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': 'Funcion Compositor (100 $e)',
                'verbose_name_plural': 'Funciones Compositor (100 $e - R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Forma240',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('forma', models.ForeignKey(help_text='240 $k – Forma normalizada (igual que 130 $k)', on_delete=django.db.models.deletion.PROTECT, to='catalogacion.autoridadformamusical')),
                ('obra', models.ForeignKey(help_text='Obra a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='formas_240', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': 'Forma (240 $k)',
                'verbose_name_plural': 'Formas (240 $k - R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Forma130',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('forma', models.ForeignKey(help_text='130 $k – Forma normalizada', on_delete=django.db.models.deletion.PROTECT, to='catalogacion.autoridadformamusical')),
                ('obra', models.ForeignKey(help_text='Obra a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='formas_130', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': 'Forma (130 $k)',
                'verbose_name_plural': 'Formas (130 $k - R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EntidadRelacionada710',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcion', models.CharField(blank=True, choices=[('coeditor', 'Coeditor'), ('dedicatario', 'Dedicatorio'), ('editor', 'Editor'), ('lugar_ejecucion', 'Lugar de ejecución'), ('lugar_estreno', 'Lugar de estreno'), ('patrocinante', 'Patrocinante')], help_text='710 $e – Función institucional (R)', max_length=50, null=True)),
                ('entidad', models.ForeignKey(help_text='710 $a – Entidad/Jurisdicción (controlado, NR)', on_delete=django.db.models.deletion.PROTECT, to='catalogacion.autoridadentidad')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entidades_relacionadas_710', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': '710 – Entidad relacionada',
                'verbose_name_plural': '710 – Entidades relacionadas (R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EnlaceUnidadConstituyente774',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='774 $t – Título (NR)', max_length=250)),
                ('numero_obra_relacionada', models.CharField(blank=True, help_text='774 $w – Número de obra relacionada (R)', max_length=50, null=True)),
                ('encabezamiento_principal', models.ForeignKey(help_text='774 $a – Encabezamiento principal (NR)', on_delete=django.db.models.deletion.PROTECT, to='catalogacion.autoridadentidad')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enlaces_unidades_774', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': '774 – Unidad constituyente',
                'verbose_name_plural': '774 – Unidades constituyentes (R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EnlaceDocumentoFuente773',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='773 $t – Título (NR)', max_length=250)),
                ('numero_obra_relacionada', models.CharField(blank=True, help_text='773 $w – Número de obra relacionada (R)', max_length=50, null=True)),
                ('encabezamiento_principal', models.ForeignKey(help_text='773 $a – Encabezamiento principal (NR)', on_delete=django.db.models.deletion.PROTECT, to='catalogacion.autoridadpersona')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enlaces_documento_fuente_773', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': '773 – Documento fuente',
                'verbose_name_plural': '773 – Documentos fuente (R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Edicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edicion', models.CharField(help_text='250 $a – Edición', max_length=500)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('obra', models.ForeignKey(help_text='Obra a la que pertenece esta edición', on_delete=django.db.models.deletion.CASCADE, related_name='ediciones', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': 'Edición (250)',
                'verbose_name_plural': 'Ediciones (250 - R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Disponible856',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='856 $u – URL del recurso disponible', max_length=500)),
                ('texto_enlace', models.CharField(blank=True, help_text='856 $y – Texto del enlace (repetible)', max_length=255, null=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibles_856', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': '856 - Disponible',
                'verbose_name_plural': '🌐 856 - Recursos disponibles',
            },
        ),
        migrations.AddField(
            model_name='designacionnumericaobra',
            name='obra',
            field=models.ForeignKey(help_text='Obra a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='designaciones_numericas', to='catalogacion.obrageneral'),
        ),
        migrations.AddField(
            model_name='descripcionfisica',
            name='obra',
            field=models.ForeignKey(help_text='Obra a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='descripciones_fisicas', to='catalogacion.obrageneral'),
        ),
        migrations.CreateModel(
            name='DatosBiograficos545',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos_biograficos', models.TextField(blank=True, help_text='545 $a – Datos biográficos del compositor (R)', null=True)),
                ('url', models.URLField(blank=True, help_text='545 $u – URL (R)', null=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datos_biograficos_545', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': '545 – Datos biográficos del compositor',
                'verbose_name_plural': '545 – Datos biográficos del compositor (R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Contenido505',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(blank=True, help_text='505 $a – Contenido (R)', null=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenidos_505', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': '505 – Contenido',
                'verbose_name_plural': '505 – Contenidos (R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CodigoPaisEntidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_pais', models.CharField(choices=[('ar', 'Argentina'), ('bo', 'Bolivia'), ('br', 'Brasil'), ('cl', 'Chile'), ('co', 'Colombia'), ('cr', 'Costa Rica'), ('cu', 'Cuba'), ('ec', 'Ecuador'), ('sv', 'El Salvador'), ('gt', 'Guatemala'), ('ho', 'Honduras'), ('mx', 'México'), ('nq', 'Nicaragua'), ('pa', 'Panamá'), ('pe', 'Perú'), ('pr', 'Puerto Rico'), ('dr', 'República Dominicana'), ('uy', 'Uruguay'), ('ve', 'Venezuela')], default='ec', help_text='044 $a – Código ISO 3166-1 alfa-2 del país', max_length=2)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(help_text='Obra a la que pertenece este código de país', on_delete=django.db.models.deletion.CASCADE, related_name='codigos_pais_entidad', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': 'País Editor/Productor (044 $a)',
                'verbose_name_plural': 'Países Editor/Productor (044 $a - R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.AddField(
            model_name='codigolengua',
            name='obra',
            field=models.ForeignKey(help_text='Obra a la que pertenece este código de lengua', on_delete=django.db.models.deletion.CASCADE, related_name='codigos_lengua', to='catalogacion.obrageneral'),
        ),
        migrations.CreateModel(
            name='CaracteristicaMusicaNotada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(help_text='Obra a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='caracteristicas_musica_notada', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': 'Característica Música Notada (348)',
                'verbose_name_plural': 'Características Música Notada (348 - R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AtribucionCompositor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atribucion', models.CharField(choices=[('atribuida', 'Atribuida'), ('certificada', 'Certificada'), ('erronea', 'Erronea')], default='certificada', help_text='100 $j – Calificador de atribucion (predeterminado: certificada)', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(help_text='Obra a la que pertenece esta atribucion', on_delete=django.db.models.deletion.CASCADE, related_name='atribuciones_compositor', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': 'Atribucion Compositor (100 $j)',
                'verbose_name_plural': 'Atribuciones Compositor (100 $j - R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Opus383',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opus', models.CharField(help_text="383 $b – Número de Opus (ej: 'Op. 27, No. 2', 'Op. 131')", max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('designacion_numerica', models.ForeignKey(help_text='Designación a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='opus', to='catalogacion.designacionnumericaobra')),
            ],
            options={
                'verbose_name': 'Opus (383 $b)',
                'verbose_name_plural': 'Opus (383 $b - R)',
                'ordering': ['designacion_numerica', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OtrasRelaciones787',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='787 $t – Título (NR)', max_length=250)),
                ('numero_obra_relacionada', models.CharField(blank=True, help_text='787 $w – Número de obra relacionada (R)', max_length=50, null=True)),
                ('encabezamiento_principal', models.ForeignKey(help_text='787 $a – Encabezamiento principal (NR)', on_delete=django.db.models.deletion.PROTECT, to='catalogacion.autoridadpersona')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otras_relaciones_787', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': '787 – Otra relación',
                'verbose_name_plural': '787 – Otras relaciones (R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProduccionPublicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcion', models.CharField(choices=[('0', 'Producción'), ('1', 'Publicación'), ('2', 'Distribución'), ('3', 'Fabricación'), ('4', 'Copyright')], default='0', help_text='264 segundo indicador – Función de la entidad', max_length=1)),
                ('lugar', models.CharField(blank=True, help_text='264 $a – Lugar de producción/publicación (R)', max_length=200, null=True)),
                ('nombre_entidad', models.CharField(blank=True, help_text='264 $b – Nombre del productor/editor/distribuidor (R)', max_length=300, null=True)),
                ('fecha', models.CharField(blank=True, help_text='264 $c – Fecha de producción/publicación (R)', max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('obra', models.ForeignKey(help_text='Obra a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='producciones_publicaciones', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': 'Producción/Publicación (264)',
                'verbose_name_plural': 'Producciones/Publicaciones (264 - R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Relacion700',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='700 $i – Relación (R)', max_length=200)),
                ('nombre_700', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones', to='catalogacion.nombrerelacionado700')),
            ],
            options={
                'verbose_name': '700 $i – Relación',
                'verbose_name_plural': '700 $i – Relaciones (R)',
                'ordering': ['nombre_700', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Solista382',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solista', models.CharField(choices=[('piano', 'Piano')], default='piano', help_text='382 $b – Solista (predeterminado: piano)', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('medio_interpretacion', models.ForeignKey(help_text='Medio de interpretación al que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='solistas', to='catalogacion.mediointerpretacion382')),
            ],
            options={
                'verbose_name': 'Solista (382 $b)',
                'verbose_name_plural': 'Solistas (382 $b - R)',
                'ordering': ['medio_interpretacion', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SubdivisionGeneral655',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdivision', models.CharField(help_text='655 $x – Subdivisión general', max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('materia655', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdivisiones', to='catalogacion.materiagenero655')),
            ],
            options={
                'verbose_name': '655 $x – Subdivisión general',
                'verbose_name_plural': '655 $x – Subdivisiones generales (R)',
                'ordering': ['materia655', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SubdivisionMateria650',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdivision', models.CharField(help_text='650 $x – Subdivisión de materia', max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('materia650', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdivisiones', to='catalogacion.materia650')),
            ],
            options={
                'verbose_name': '650 $x – Subdivisión de materia',
                'verbose_name_plural': '650 $x – Subdivisiones de materia (R)',
                'ordering': ['materia650', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Sumario520',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sumario', models.TextField(blank=True, help_text='520 $a – Sumario (NR)', null=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sumarios_520', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': '520 – Sumario',
                'verbose_name_plural': '520 – Sumarios (R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Tecnica340',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecnica', models.CharField(choices=[('autógrafo', 'Autógrafo'), ('posible autógrafo', 'Posible autógrafo'), ('manuscrito', 'Manuscrito'), ('manuscrito de copista no identificado', 'Manuscrito de copista no identificado'), ('impreso', 'Impreso'), ('fotocopia de manuscrito', 'Fotocopia de manuscrito'), ('fotocopia de impreso', 'Fotocopia de impreso')], help_text='340 $d – Técnica de registro (repetible dentro de cada 340)', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('medio_fisico', models.ForeignKey(help_text='Medio físico al que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='tecnicas', to='catalogacion.mediofisico')),
            ],
            options={
                'verbose_name': 'Técnica (340 $d)',
                'verbose_name_plural': 'Técnicas (340 $d - R)',
                'ordering': ['medio_fisico', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TerminoAsociado700',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termino', models.CharField(help_text='700 $c – Término asociado al nombre (R)', max_length=100)),
                ('nombre_700', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminos_asociados', to='catalogacion.nombrerelacionado700')),
            ],
            options={
                'verbose_name': '700 $c – Término asociado',
                'verbose_name_plural': '700 $c – Términos asociados (R)',
                'ordering': ['nombre_700', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TituloAlternativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='246 $a – Título abreviado o alternativo', max_length=500)),
                ('resto_titulo', models.CharField(blank=True, help_text='246 $b – Resto del título variante', max_length=500, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(help_text='Obra a la que pertenece este título alternativo', on_delete=django.db.models.deletion.CASCADE, related_name='titulos_alternativos', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': 'Título Alternativo (246)',
                'verbose_name_plural': 'Títulos Alternativos (246)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TituloSerie490',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_serie', models.CharField(help_text="490 $a – Título/mención de la serie (ej: 'Colección Támesis. Serie A')", max_length=300)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('mencion_serie', models.ForeignKey(help_text='Mención de serie a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='titulos', to='catalogacion.mencionserie490')),
            ],
            options={
                'verbose_name': 'Título Serie (490 $a)',
                'verbose_name_plural': 'Títulos Serie (490 $a - R)',
                'ordering': ['mencion_serie', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Ubicacion852',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion_persona', models.CharField(help_text='852 $a – Institución o persona (no repetible)', max_length=255)),
                ('signatura_original', models.CharField(blank=True, help_text='852 $h – Signatura original (no repetible)', max_length=255, null=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones_852', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': '852 - Ubicación',
                'verbose_name_plural': '📍 852 - Ubicaciones',
            },
        ),
        migrations.CreateModel(
            name='Estanteria852',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estanteria', models.CharField(help_text='852 $c – Estantería (repetible)', max_length=255)),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estanterias', to='catalogacion.ubicacion852')),
            ],
            options={
                'verbose_name': '852 $c – Estantería',
                'verbose_name_plural': '📚 852 $c – Estanterías',
            },
        ),
        migrations.CreateModel(
            name='VolumenSerie490',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volumen', models.CharField(help_text="490 $v – Designación de volumen (ej: '260', 'Vol. 5', 'Tomo III')", max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('mencion_serie', models.ForeignKey(help_text='Mención de serie a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='volumenes', to='catalogacion.mencionserie490')),
            ],
            options={
                'verbose_name': 'Volumen (490 $v)',
                'verbose_name_plural': 'Volúmenes (490 $v - R)',
                'ordering': ['mencion_serie', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Formato348',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formato', models.CharField(choices=[('parte', 'Parte'), ('partitura', 'Partitura'), ('partitura de coro', 'Partitura de coro'), ('partitura piano vocal', 'Partitura piano-vocal')], help_text='348 $a – Formato de presentación (repetible dentro de cada 348)', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('caracteristica', models.ForeignKey(help_text='Característica a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='formatos', to='catalogacion.caracteristicamusicanotada')),
            ],
            options={
                'verbose_name': 'Formato (348 $a)',
                'verbose_name_plural': 'Formatos (348 $a - R)',
                'ordering': ['caracteristica', 'id'],
                'unique_together': {('caracteristica', 'formato')},
            },
        ),
        migrations.AddIndex(
            model_name='obrageneral',
            index=models.Index(fields=['num_control'], name='catalogacio_num_con_5cfcb5_idx'),
        ),
        migrations.AddIndex(
            model_name='obrageneral',
            index=models.Index(fields=['tipo_registro'], name='catalogacio_tipo_re_aa2327_idx'),
        ),
        migrations.AddIndex(
            model_name='obrageneral',
            index=models.Index(fields=['nivel_bibliografico'], name='catalogacio_nivel_b_8e99cf_idx'),
        ),
        migrations.AddIndex(
            model_name='obrageneral',
            index=models.Index(fields=['-fecha_creacion_sistema'], name='catalogacio_fecha_c_1c88ca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='incipitmusical',
            unique_together={('obra', 'numero_obra', 'numero_movimiento', 'numero_pasaje')},
        ),
        migrations.AlterUniqueTogether(
            name='codigopaisentidad',
            unique_together={('obra', 'codigo_pais')},
        ),
    ]
