# Generated by Django 5.2.7 on 2025-10-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObraGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_registro', models.CharField(default='n', editable=False, max_length=1)),
                ('tipo_registro', models.CharField(choices=[('c', 'Música impresa'), ('d', 'Música manuscrita')], default='d', max_length=1)),
                ('nivel_bibliografico', models.CharField(choices=[('a', 'Parte componente'), ('c', 'Colección'), ('m', 'Obra independiente')], default='m', max_length=1)),
                ('num_control', models.CharField(editable=False, max_length=6, unique=True)),
                ('fecha_hora_ultima_transaccion', models.CharField(editable=False, max_length=14)),
                ('codigo_informacion', models.CharField(editable=False, max_length=40)),
                ('isbn', models.CharField(blank=True, help_text='020 $a – ISBN tomado tal como aparece en la fuente. Genera vista de usuario.', max_length=20, null=True)),
                ('ismn', models.CharField(blank=True, help_text='024 $a – ISMN tomado tal como aparece en la fuente. Genera vista de usuario.', max_length=20, null=True)),
                ('numero_editor', models.CharField(blank=True, help_text='028 $a – Número de plancha, placa o código distintivo del editor. Genera vista de usuario.', max_length=50, null=True)),
                ('indicador_028', models.CharField(default='20', help_text="028 Indicador. Predeterminado '20', con opción de cambiar.", max_length=2)),
                ('incipit_num_obra', models.PositiveIntegerField(default=1, help_text='031 $a – Número de la obra.')),
                ('incipit_num_movimiento', models.PositiveIntegerField(default=1, help_text='031 $b – Número del movimiento.')),
                ('incipit_num_pasaje', models.PositiveIntegerField(default=1, help_text='031 $c – Número de pasaje.')),
                ('incipit_titulo', models.CharField(blank=True, help_text='031 $d – Título o encabezamiento del íncipit.', max_length=100, null=True)),
                ('incipit_voz_instrumento', models.CharField(blank=True, help_text='031 $m – Voz o instrumento.', max_length=100, null=True)),
                ('incipit_notacion', models.TextField(blank=True, help_text='031 $p – Íncipit musical codificado.', null=True)),
                ('incipit_url', models.URLField(blank=True, help_text='031 $u – URL del íncipit en otra base de datos.', null=True)),
                ('centro_catalogador', models.CharField(default='UNL', help_text='040 $a – Centro catalogador de origen (UNL).', max_length=10)),
                ('codigo_lengua', models.CharField(choices=[('spa', 'Español'), ('eng', 'Inglés'), ('fra', 'Francés'), ('ger', 'Alemán'), ('ita', 'Italiano'), ('lat', 'Latín')], default='spa', help_text='041 $a – Código de lengua MARC21.', max_length=3)),
                ('codigo_pais', models.CharField(choices=[('ec', 'Ecuador'), ('us', 'Estados Unidos'), ('es', 'España'), ('fr', 'Francia'), ('it', 'Italia'), ('de', 'Alemania')], default='ec', help_text='044 $a – Código MARC del país.', max_length=3)),
                ('clasif_institucion', models.CharField(default='UNL', help_text='092 $a – Institución (duplica 040 $a).', max_length=50)),
                ('clasif_proyecto', models.CharField(default='BLMP', help_text='092 $b – Proyecto asociado.', max_length=50)),
                ('clasif_pais', models.CharField(default='EC', help_text='092 $c – País (duplica 044 $a).', max_length=50)),
                ('clasif_ms_imp', models.CharField(choices=[('Ms', 'Manuscrito'), ('Imp', 'Impreso')], default='Ms', help_text='092 $d – Ms o Imp. Tipo de material.', max_length=3)),
                ('clasif_num_control', models.CharField(editable=False, help_text='092 $0 – Duplica el número de control (001).', max_length=6)),
            ],
        ),
    ]
