# Generated by Django 5.2.8 on 2025-12-18 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incipitmusical',
            name='paec_full',
            field=models.TextField(blank=True, help_text="PAEC completo para render en modo vista. Ej: %G-2 $xFCGD @2/2 '2G4B/B''2E8EDC/'B''C'BABA/", null=True),
        ),
        migrations.AddField(
            model_name='incipitmusical',
            name='transposicion',
            field=models.CharField(blank=True, help_text='Transposición asociada al íncipit (si aplica).', max_length=32, null=True),
        ),
    ]
