# Generated by Django 5.2.7 on 2025-11-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materia650',
            options={'ordering': ['obra', 'id'], 'verbose_name': '650 — Materia (Tema)', 'verbose_name_plural': '650 — Materias (Temas)'},
        ),
        migrations.AlterModelOptions(
            name='materiagenero655',
            options={'ordering': ['obra', 'id'], 'verbose_name': '655 — Materia (Género/forma)', 'verbose_name_plural': '655 — Materias (Género/forma)'},
        ),
        migrations.AlterModelOptions(
            name='subdivisiongeneral655',
            options={'ordering': ['materia655', 'id'], 'verbose_name': '655 $x — Subdivisión general', 'verbose_name_plural': '655 $x — Subdivisiones generales (R)'},
        ),
        migrations.AlterModelOptions(
            name='subdivisionmateria650',
            options={'ordering': ['materia650', 'id'], 'verbose_name': '650 $x — Subdivisión de materia', 'verbose_name_plural': '650 $x — Subdivisiones de materia (R)'},
        ),
        migrations.AlterField(
            model_name='materia650',
            name='materia',
            field=models.CharField(help_text='650 $a — Materia principal', max_length=200),
        ),
        migrations.AlterField(
            model_name='materiagenero655',
            name='materia',
            field=models.CharField(help_text='655 $a — Materia (género/forma)', max_length=200),
        ),
        migrations.AlterField(
            model_name='subdivisiongeneral655',
            name='subdivision',
            field=models.CharField(help_text='655 $x — Subdivisión general', max_length=200),
        ),
        migrations.AlterField(
            model_name='subdivisionmateria650',
            name='subdivision',
            field=models.CharField(help_text='650 $x — Subdivisión de materia', max_length=200),
        ),
    ]
