# Generated by Django 5.1.2 on 2025-11-10 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obrageneral',
            name='institucion_persona_852a',
            field=models.ForeignKey(blank=True, help_text='852 $a – Institución o persona (NR). Enlace a autoridad institucional.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='obras_ubicacion_852a', to='catalogacion.autoridadentidad'),
        ),
    ]
