# Generated by Django 5.1.2 on 2025-11-20 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enlacedocumentofuente773',
            name='encabezamiento_principal',
            field=models.ForeignKey(help_text='773 $a – Encabezamiento principal (NR)', on_delete=django.db.models.deletion.PROTECT, to='catalogacion.autoridadpersona'),
        ),
        migrations.AlterField(
            model_name='enlaceunidadconstituyente774',
            name='encabezamiento_principal',
            field=models.ForeignKey(help_text='774 $a – Encabezamiento principal (NR)', on_delete=django.db.models.deletion.PROTECT, to='catalogacion.autoridadpersona'),
        ),
        migrations.AlterField(
            model_name='otrasrelaciones787',
            name='encabezamiento_principal',
            field=models.ForeignKey(help_text='787 $a – Encabezamiento principal (NR)', on_delete=django.db.models.deletion.PROTECT, to='catalogacion.autoridadpersona'),
        ),
    ]
