# Generated by Django 5.2.8 on 2026-01-30 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='obrageneral',
            new_name='catalogacio_num_con_5cfcb5_idx',
            old_name='catalogacio_num_con_24e3b6_idx',
        ),
        migrations.RenameIndex(
            model_name='obrageneral',
            new_name='catalogacio_tipo_re_aa2327_idx',
            old_name='catalogacio_tipo_re_8a21ab_idx',
        ),
        migrations.RenameIndex(
            model_name='obrageneral',
            new_name='catalogacio_nivel_b_8e99cf_idx',
            old_name='catalogacio_nivel_b_00223e_idx',
        ),
        migrations.RenameIndex(
            model_name='obrageneral',
            new_name='catalogacio_tipo_re_39aef1_idx',
            old_name='catalogacio_tipo_re_b50116_idx',
        ),
        migrations.RenameIndex(
            model_name='obrageneral',
            new_name='catalogacio_fecha_c_1c88ca_idx',
            old_name='catalogacio_fecha_c_2cc522_idx',
        ),
        migrations.RenameIndex(
            model_name='obrageneral',
            new_name='catalogacio_titulo__013283_idx',
            old_name='catalogacio_titulo__a0d8a2_idx',
        ),
        migrations.AlterModelTable(
            name='obrageneral',
            table=None,
        ),
    ]
