# Generated by Django 5.2.7 on 2025-10-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObraGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_control', models.IntegerField(max_length=6, unique=True)),
                ('fecha_hora_ultima_transaccion', models.DateTimeField(auto_now=True)),
                ('codigo_informacion', models.CharField(blank=True, max_length=39, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ObraMarc',
        ),
    ]
