# Generated by Django 5.1.2 on 2025-12-08 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia650',
            name='materia',
            field=models.ForeignKey(blank=True, help_text='650 $a — Materia (NR)', null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogacion.autoridadmateria'),
        ),
        migrations.AlterField(
            model_name='materiagenero655',
            name='materia',
            field=models.ForeignKey(blank=True, help_text='655 $a — Género/Forma (NR)', null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogacion.autoridadformamusical'),
        ),
    ]
