# Generated by Django 5.2.7 on 2025-10-31 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obrageneral',
            name='fecha_publicacion',
        ),
        migrations.RemoveField(
            model_name='obrageneral',
            name='lugar_publicacion',
        ),
        migrations.RemoveField(
            model_name='obrageneral',
            name='nombre_editor',
        ),
        migrations.AddField(
            model_name='obrageneral',
            name='fecha_produccion_264',
            field=models.CharField(blank=True, help_text='264 $c – Fecha de producción, publicación, distribución, manufactura o copyright', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='obrageneral',
            name='lugar_produccion_264',
            field=models.CharField(blank=True, help_text='264 $a – Lugar de producción, publicación, distribución, manufactura', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='obrageneral',
            name='nombre_productor_264',
            field=models.CharField(blank=True, help_text='264 $b – Nombre del productor, editor, distribuidor, fabricante', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='obrageneral',
            name='compositor_autoria',
            field=models.CharField(blank=True, choices=[('atribuida', 'Atribuida'), ('certificada', 'Certificada')], default='certificada', help_text='100 $j – Calificador de atribución', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='obrageneral',
            name='compositor_funcion',
            field=models.CharField(blank=True, choices=[('arreglista', 'Arreglista'), ('compositor', 'Compositor')], default='compositor', help_text='100 $e – Función (predeterminado: compositor)', max_length=20, null=True),
        ),
    ]
