# Generated by Django 5.1.2 on 2025-12-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoridadpersona',
            name='coordenadas_biograficas',
            field=models.CharField(blank=True, help_text='Coordenadas biográficas: año nacimiento - año muerte', max_length=50, null=True),
        ),
    ]
