# Generated by Django 5.2.7 on 2025-10-30 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obrageneral',
            name='compositor_apellidos_nombres',
            field=models.CharField(blank=True, help_text='100 $a – Apellidos, Nombres del compositor. Cruzar con campos 600 y 700.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='obrageneral',
            name='compositor_autoria',
            field=models.CharField(blank=True, choices=[('atribuida', 'Atribuida'), ('certificada', 'Certificada'), ('errónea', 'Errónea')], default='certificada', help_text='100 $j – Autoría (R - Repetible).', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='obrageneral',
            name='compositor_coordenadas_biograficas',
            field=models.CharField(blank=True, help_text='100 $d – Coordenadas biográficas (fecha nacimiento - fecha muerte).', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='obrageneral',
            name='compositor_funcion',
            field=models.CharField(blank=True, choices=[('arreglista', 'Arreglista'), ('coeditor', 'Coeditor'), ('compilador', 'Compilador'), ('compositor', 'Compositor'), ('copista', 'Copista'), ('dedicatario', 'Dedicatario'), ('editor', 'Editor'), ('prologuista', 'Prologuista')], default='compositor', help_text='100 $e – Función (R - Repetible).', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='obrageneral',
            name='titulo_uniforme',
            field=models.CharField(blank=True, help_text='130 $a – Título uniforme.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='obrageneral',
            name='titulo_uniforme_arreglo',
            field=models.CharField(blank=True, default='arreglo', help_text='130 $o – Arreglo (NR - No Repetible).', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='obrageneral',
            name='titulo_uniforme_medio_interpretacion',
            field=models.CharField(blank=True, default='piano', help_text='130 $m – Medio de interpretación (R - Repetible). Ej: piano.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='obrageneral',
            name='titulo_uniforme_nombre_parte_seccion',
            field=models.CharField(blank=True, help_text='130 $p – Nombre de parte o sección de la obra (R - Repetible).', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='obrageneral',
            name='titulo_uniforme_num_parte_seccion',
            field=models.CharField(blank=True, help_text='130 $n – Número de parte o sección de la obra (R - Repetible).', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='obrageneral',
            name='titulo_uniforme_subencabezamiento_forma',
            field=models.CharField(blank=True, choices=[('adaptación', 'Adaptación'), ('boceto', 'Boceto'), ('fragmento', 'Fragmento'), ('selección', 'Selección'), ('tema con variaciones', 'Tema con variaciones')], help_text='130 $k – Subencabezamiento de forma (R - Repetible). Cruzar con campo 655.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='obrageneral',
            name='titulo_uniforme_tonalidad',
            field=models.CharField(blank=True, choices=[('Do mayor', 'Do mayor'), ('Do menor', 'Do menor'), ('Do# mayor', 'Do# mayor'), ('Do# menor', 'Do# menor'), ('Reb mayor', 'Reb mayor'), ('Reb menor', 'Reb menor'), ('Re mayor', 'Re mayor'), ('Re menor', 'Re menor'), ('Mib mayor', 'Mib mayor'), ('Mib menor', 'Mib menor'), ('Mi mayor', 'Mi mayor'), ('Mi menor', 'Mi menor'), ('Fa mayor', 'Fa mayor'), ('Fa menor', 'Fa menor'), ('Fa# mayor', 'Fa# mayor'), ('Fa# menor', 'Fa# menor'), ('Sol mayor', 'Sol mayor'), ('Sol menor', 'Sol menor'), ('Sol# mayor', 'Sol# mayor'), ('Sol# menor', 'Sol# menor'), ('Lab mayor', 'Lab mayor'), ('Lab menor', 'Lab menor'), ('La mayor', 'La mayor'), ('La menor', 'La menor'), ('Sib mayor', 'Sib mayor'), ('Sib menor', 'Sib menor'), ('Si mayor', 'Si mayor'), ('Si menor', 'Si menor')], help_text='130 $r – Tonalidad (NR - No Repetible). 24 tonalidades mayores y menores.', max_length=15, null=True),
        ),
    ]
