# Generated by Django 5.2.7 on 2025-11-13 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produccionpublicacion',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='produccionpublicacion',
            name='lugar',
        ),
        migrations.RemoveField(
            model_name='produccionpublicacion',
            name='nombre_entidad',
        ),
        migrations.AlterField(
            model_name='produccionpublicacion',
            name='funcion',
            field=models.CharField(choices=[('0', 'Producción'), ('1', 'Publicación'), ('2', 'Distribución'), ('3', 'Fabricación'), ('4', 'Copyright')], default='1', help_text='264 segundo indicador – Función de la entidad', max_length=1),
        ),
        migrations.CreateModel(
            name='Fecha264',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(help_text='264 $c – Fecha de producción/publicación', max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('produccion_publicacion', models.ForeignKey(help_text='Producción/Publicación a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='fechas', to='catalogacion.produccionpublicacion')),
            ],
            options={
                'verbose_name': 'Fecha (264 $c)',
                'verbose_name_plural': 'Fechas (264 $c - R)',
                'ordering': ['produccion_publicacion', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Lugar264',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(help_text='264 $a – Lugar de producción/publicación', max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('produccion_publicacion', models.ForeignKey(help_text='Producción/Publicación a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='lugares', to='catalogacion.produccionpublicacion')),
            ],
            options={
                'verbose_name': 'Lugar (264 $a)',
                'verbose_name_plural': 'Lugares (264 $a - R)',
                'ordering': ['produccion_publicacion', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NombreEntidad264',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='264 $b – Nombre del productor/editor/distribuidor', max_length=300)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('produccion_publicacion', models.ForeignKey(help_text='Producción/Publicación a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='entidades', to='catalogacion.produccionpublicacion')),
            ],
            options={
                'verbose_name': 'Nombre de Entidad (264 $b)',
                'verbose_name_plural': 'Nombres de Entidades (264 $b - R)',
                'ordering': ['produccion_publicacion', 'id'],
            },
        ),
    ]
