# Generated by Django 5.1.2 on 2025-12-10 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidadrelacionada710',
            name='obra',
            field=models.ForeignKey(blank=True, help_text='710 $a – Entidad relacionada (NR)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entidades_relacionadas_710', to='catalogacion.obrageneral'),
        ),
    ]
