# Generated by Django 5.1.2 on 2026-01-19 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='borradorobra',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó este borrador', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borradores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='obrageneral',
            name='catalogador',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obras_catalogadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='obrageneral',
            name='modificado_por',
            field=models.ForeignKey(blank=True, help_text='Último usuario que modificó el registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obras_modificadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
