# Generated by Django 5.1.2 on 2026-02-24 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncionInstitucional710',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcion', models.CharField(choices=[('coeditor', 'Coeditor'), ('dedicatario', 'Dedicatario'), ('editor', 'Editor'), ('lugar_ejecucion', 'Lugar de ejecución'), ('lugar_estreno', 'Lugar de estreno'), ('patrocinante', 'Patrocinante')], help_text='710 $e – Función institucional', max_length=50)),
            ],
            options={
                'verbose_name': '710 $e – Función institucional',
                'verbose_name_plural': '710 $e – Funciones institucionales',
            },
        ),
        migrations.CreateModel(
            name='SubdivisionCronologica650',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdivision', models.CharField(help_text='650 $z — Subdivisión geográfica (R)', max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '650 $z — Subdivisión geográfica',
                'verbose_name_plural': '650 $z — Subdivisiones geográficas (R)',
                'ordering': ['materia650', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SubdivisionCronologica655',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdivision', models.CharField(help_text='655 $z — Subdivisión cronológica (R)', max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '655 $z — Subdivisión cronológica',
                'verbose_name_plural': '655 $z — Subdivisiones cronológicas (R)',
                'ordering': ['materia655', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='subdivisionmateria650',
            options={'ordering': ['materia650', 'id'], 'verbose_name': '650 $y — Subdivisión cronológica', 'verbose_name_plural': '650 $y — Subdivisión cronológica (R)'},
        ),
        migrations.RenameIndex(
            model_name='obrageneral',
            new_name='catalogacio_num_con_5cfcb5_idx',
            old_name='catalogacio_num_con_24e3b6_idx',
        ),
        migrations.RenameIndex(
            model_name='obrageneral',
            new_name='catalogacio_tipo_re_aa2327_idx',
            old_name='catalogacio_tipo_re_8a21ab_idx',
        ),
        migrations.RenameIndex(
            model_name='obrageneral',
            new_name='catalogacio_nivel_b_8e99cf_idx',
            old_name='catalogacio_nivel_b_00223e_idx',
        ),
        migrations.RenameIndex(
            model_name='obrageneral',
            new_name='catalogacio_tipo_re_39aef1_idx',
            old_name='catalogacio_tipo_re_b50116_idx',
        ),
        migrations.RenameIndex(
            model_name='obrageneral',
            new_name='catalogacio_fecha_c_1c88ca_idx',
            old_name='catalogacio_fecha_c_2cc522_idx',
        ),
        migrations.RenameIndex(
            model_name='obrageneral',
            new_name='catalogacio_titulo__013283_idx',
            old_name='catalogacio_titulo__a0d8a2_idx',
        ),
        migrations.RemoveField(
            model_name='entidadrelacionada710',
            name='funcion',
        ),
        migrations.AddField(
            model_name='obrageneral',
            name='fecha_publicacion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se publicó la obra', null=True),
        ),
        migrations.AddField(
            model_name='obrageneral',
            name='publicada',
            field=models.BooleanField(db_index=True, default=False, help_text='Indica si la obra está publicada en el catálogo público'),
        ),
        migrations.AlterField(
            model_name='codigopaisentidad',
            name='codigo_pais',
            field=models.CharField(choices=[('ar', 'Argentina'), ('bf', 'Bahamas'), ('bb', 'Barbados'), ('bh', 'Belice'), ('bo', 'Bolivia'), ('br', 'Brasil'), ('cl', 'Chile'), ('co', 'Colombia'), ('cr', 'Costa Rica'), ('cu', 'Cuba'), ('dr', 'República Dominicana'), ('ec', 'Ecuador'), ('sv', 'El Salvador'), ('fg', 'Guayana Francesa'), ('gp', 'Guadalupe'), ('gt', 'Guatemala'), ('gy', 'Guyana'), ('ht', 'Haití'), ('ho', 'Honduras'), ('jm', 'Jamaica'), ('mq', 'Martinica'), ('mx', 'México'), ('na', 'Antillas Neerlandesas'), ('nq', 'Nicaragua'), ('pa', 'Panamá'), ('py', 'Paraguay'), ('pe', 'Perú'), ('pr', 'Puerto Rico'), ('sr', 'Surinam'), ('tg', 'Trinidad y Tobago'), ('uy', 'Uruguay'), ('ve', 'Venezuela'), ('vi', 'Islas Vírgenes'), ('xxc', 'Canadá'), ('xxu', 'Estados Unidos'), ('aa', 'Albania'), ('an', 'Andorra'), ('au', 'Austria'), ('ba', 'Bosnia y Herzegovina'), ('be', 'Bélgica'), ('bu', 'Bulgaria'), ('bw', 'Bielorrusia'), ('ci', 'Croacia'), ('cy', 'Chipre'), ('xr', 'República Checa'), ('dk', 'Dinamarca'), ('er', 'Estonia'), ('fi', 'Finlandia'), ('fr', 'Francia'), ('gw', 'Alemania'), ('gr', 'Grecia'), ('hu', 'Hungría'), ('ic', 'Islandia'), ('ie', 'Irlanda'), ('it', 'Italia'), ('lv', 'Letonia'), ('lh', 'Liechtenstein'), ('li', 'Lituania'), ('lu', 'Luxemburgo'), ('mk', 'Macedonia del Norte'), ('mm', 'Malta'), ('mv', 'Moldavia'), ('mc', 'Mónaco'), ('mo', 'Montenegro'), ('ne', 'Países Bajos'), ('no', 'Noruega'), ('pl', 'Polonia'), ('po', 'Portugal'), ('rm', 'Rumania'), ('ru', 'Rusia'), ('sm', 'San Marino'), ('rb', 'Serbia'), ('xo', 'Eslovaquia'), ('xv', 'Eslovenia'), ('sp', 'España'), ('sw', 'Suecia'), ('sz', 'Suiza'), ('tu', 'Turquía'), ('un', 'Ucrania'), ('enk', 'Reino Unido'), ('vc', 'Ciudad del Vaticano'), ('af', 'Afganistán'), ('ai', 'Armenia'), ('aj', 'Azerbaiyán'), ('bg', 'Bangladés'), ('bt', 'Bután'), ('bx', 'Brunéi'), ('cb', 'Camboya'), ('cc', 'China'), ('gs', 'Georgia'), ('ii', 'India'), ('io', 'Indonesia'), ('ir', 'Irán'), ('iq', 'Irak'), ('is', 'Israel'), ('ja', 'Japón'), ('jo', 'Jordania'), ('kz', 'Kazajistán'), ('kn', 'Corea del Norte'), ('ko', 'Corea del Sur'), ('ku', 'Kuwait'), ('kg', 'Kirguistán'), ('ls', 'Laos'), ('le', 'Líbano'), ('my', 'Malasia'), ('xc', 'Maldivas'), ('mp', 'Mongolia'), ('bm', 'Myanmar'), ('np', 'Nepal'), ('pk', 'Pakistán'), ('ph', 'Filipinas'), ('qa', 'Catar'), ('su', 'Arabia Saudita'), ('si', 'Singapur'), ('ce', 'Sri Lanka'), ('sy', 'Siria'), ('ta', 'Tayikistán'), ('th', 'Tailandia'), ('ti', 'Timor Oriental'), ('tk', 'Turkmenistán'), ('ts', 'Emiratos Árabes Unidos'), ('uz', 'Uzbekistán'), ('vm', 'Vietnam'), ('ye', 'Yemen')], default='ec', help_text='044 $a — Código MARC21 del país', max_length=5),
        ),
        migrations.AlterField(
            model_name='funcion700',
            name='funcion',
            field=models.CharField(choices=[('arreglista', 'Arreglista'), ('coeditor', 'Coeditor'), ('compilador', 'Compilador'), ('compositor', 'Compositor'), ('copista', 'Copista'), ('dedicatario', 'Dedicatario'), ('editor', 'Editor'), ('prologuista', 'Prologuista')], help_text='700 $e – Función (R)', max_length=30),
        ),
        migrations.AlterField(
            model_name='incipitmusical',
            name='tiempo',
            field=models.CharField(blank=True, help_text='031 $o – Compás', max_length=20),
        ),
        migrations.AlterField(
            model_name='incipitmusical',
            name='titulo_encabezamiento',
            field=models.CharField(blank=True, help_text='031 $d – Tempo', max_length=200),
        ),
        migrations.AlterField(
            model_name='mediointerpretacion382',
            name='solista',
            field=models.CharField(blank=True, default='piano', help_text='382 $b — Solista (predeterminado: piano)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='obrageneral',
            name='ms_imp',
            field=models.CharField(blank=True, choices=[('autógrafo', 'Autógrafo'), ('posible autógrafo', 'Posible autógrafo'), ('manuscrito', 'Manuscrito'), ('manuscrito digital', 'Manuscrito digital'), ('manuscrito de copista no identificado', 'Manuscrito de copista no identificado'), ('impreso', 'Impreso'), ('fotocopia de manuscrito', 'Fotocopia de manuscrito'), ('fotocopia de impreso', 'Fotocopia de impreso')], help_text='340 $d — Técnica', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subdivisionmateria650',
            name='subdivision',
            field=models.CharField(help_text='650 $y — Subdivisión cronológica  (R)', max_length=200),
        ),
        migrations.AlterField(
            model_name='tituloalternativo',
            name='subtitulo',
            field=models.CharField(blank=True, help_text='246 $b – Subtitulo', max_length=500, null=True),
        ),
        migrations.AlterModelTable(
            name='obrageneral',
            table=None,
        ),
        migrations.AddField(
            model_name='funcioninstitucional710',
            name='entidad_710',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funciones_institucionales', to='catalogacion.entidadrelacionada710'),
        ),
        migrations.AddField(
            model_name='subdivisioncronologica650',
            name='materia650',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdivisiones_geograficas', to='catalogacion.materia650'),
        ),
        migrations.AddField(
            model_name='subdivisioncronologica655',
            name='materia655',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdivisiones_cronologicas', to='catalogacion.materiagenero655'),
        ),
    ]
