# Generated by Django 5.2.8 on 2026-02-01 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0002_remove_custom_db_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigopaisentidad',
            name='codigo_pais',
            field=models.CharField(choices=[('ar', 'Argentina'), ('bf', 'Bahamas'), ('bb', 'Barbados'), ('bh', 'Belice'), ('bo', 'Bolivia'), ('br', 'Brasil'), ('cl', 'Chile'), ('co', 'Colombia'), ('cr', 'Costa Rica'), ('cu', 'Cuba'), ('dr', 'República Dominicana'), ('ec', 'Ecuador'), ('sv', 'El Salvador'), ('fg', 'Guayana Francesa'), ('gp', 'Guadalupe'), ('gt', 'Guatemala'), ('gy', 'Guyana'), ('ht', 'Haití'), ('ho', 'Honduras'), ('jm', 'Jamaica'), ('mq', 'Martinica'), ('mx', 'México'), ('na', 'Antillas Neerlandesas'), ('nq', 'Nicaragua'), ('pa', 'Panamá'), ('py', 'Paraguay'), ('pe', 'Perú'), ('pr', 'Puerto Rico'), ('sr', 'Surinam'), ('tg', 'Trinidad y Tobago'), ('uy', 'Uruguay'), ('ve', 'Venezuela'), ('vi', 'Islas Vírgenes'), ('xxc', 'Canadá'), ('xxu', 'Estados Unidos'), ('aa', 'Albania'), ('an', 'Andorra'), ('au', 'Austria'), ('ba', 'Bosnia y Herzegovina'), ('be', 'Bélgica'), ('bu', 'Bulgaria'), ('bw', 'Bielorrusia'), ('ci', 'Croacia'), ('cy', 'Chipre'), ('xr', 'República Checa'), ('dk', 'Dinamarca'), ('er', 'Estonia'), ('fi', 'Finlandia'), ('fr', 'Francia'), ('gw', 'Alemania'), ('gr', 'Grecia'), ('hu', 'Hungría'), ('ic', 'Islandia'), ('ie', 'Irlanda'), ('it', 'Italia'), ('lv', 'Letonia'), ('lh', 'Liechtenstein'), ('li', 'Lituania'), ('lu', 'Luxemburgo'), ('mk', 'Macedonia del Norte'), ('mm', 'Malta'), ('mv', 'Moldavia'), ('mc', 'Mónaco'), ('mo', 'Montenegro'), ('ne', 'Países Bajos'), ('no', 'Noruega'), ('pl', 'Polonia'), ('po', 'Portugal'), ('rm', 'Rumania'), ('ru', 'Rusia'), ('sm', 'San Marino'), ('rb', 'Serbia'), ('xo', 'Eslovaquia'), ('xv', 'Eslovenia'), ('sp', 'España'), ('sw', 'Suecia'), ('sz', 'Suiza'), ('tu', 'Turquía'), ('un', 'Ucrania'), ('enk', 'Reino Unido'), ('vc', 'Ciudad del Vaticano'), ('af', 'Afganistán'), ('ai', 'Armenia'), ('aj', 'Azerbaiyán'), ('bg', 'Bangladés'), ('bt', 'Bután'), ('bx', 'Brunéi'), ('cb', 'Camboya'), ('cc', 'China'), ('gs', 'Georgia'), ('ii', 'India'), ('io', 'Indonesia'), ('ir', 'Irán'), ('iq', 'Irak'), ('is', 'Israel'), ('ja', 'Japón'), ('jo', 'Jordania'), ('kz', 'Kazajistán'), ('kn', 'Corea del Norte'), ('ko', 'Corea del Sur'), ('ku', 'Kuwait'), ('kg', 'Kirguistán'), ('ls', 'Laos'), ('le', 'Líbano'), ('my', 'Malasia'), ('xc', 'Maldivas'), ('mp', 'Mongolia'), ('bm', 'Myanmar'), ('np', 'Nepal'), ('pk', 'Pakistán'), ('ph', 'Filipinas'), ('qa', 'Catar'), ('su', 'Arabia Saudita'), ('si', 'Singapur'), ('ce', 'Sri Lanka'), ('sy', 'Siria'), ('ta', 'Tayikistán'), ('th', 'Tailandia'), ('ti', 'Timor Oriental'), ('tk', 'Turkmenistán'), ('ts', 'Emiratos Árabes Unidos'), ('uz', 'Uzbekistán'), ('vm', 'Vietnam'), ('ye', 'Yemen')], default='ec', help_text='044 $a — Código MARC21 del país', max_length=5),
        ),
        migrations.AlterField(
            model_name='obrageneral',
            name='ms_imp',
            field=models.CharField(blank=True, choices=[('autógrafo', 'Autógrafo'), ('posible autógrafo', 'Posible autógrafo'), ('manuscrito', 'Manuscrito'), ('manuscrito digital', 'Manuscrito digital'), ('manuscrito de copista no identificado', 'Manuscrito de copista no identificado'), ('impreso', 'Impreso'), ('fotocopia de manuscrito', 'Fotocopia de manuscrito'), ('fotocopia de impreso', 'Fotocopia de impreso')], help_text='340 $d — Técnica', max_length=200, null=True),
        ),
    ]
