# Generated by Django 5.1.2 on 2026-01-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0002_borradorobra_usuario_obrageneral_catalogador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obrageneral',
            name='formato',
            field=models.CharField(blank=True, choices=[('parte', 'Parte'), ('partitura de piano', 'Partitura de piano'), ('partitura de coro', 'Partitura de coro'), ('partitura piano vocal', 'Partitura piano vocal')], help_text='348 $a — Formato de la música notada', max_length=100, null=True),
        ),
    ]
