# Generated by Django 5.1.2 on 2025-12-11 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0002_alter_entidadrelacionada710_obra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidadrelacionada710',
            name='entidad',
            field=models.ForeignKey(blank=True, help_text='710 $a – Entidad relacionada (NR)', null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogacion.autoridadentidad'),
        ),
        migrations.AlterField(
            model_name='nombrerelacionado700',
            name='persona',
            field=models.ForeignKey(blank=True, help_text='700 $a – Apellidos, Nombres (NR, autoridad)', null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogacion.autoridadpersona'),
        ),
    ]
