# Generated by Django 5.2.8 on 2025-11-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0002_alter_enlacedocumentofuente773_encabezamiento_principal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incipitmusical',
            name='armadura',
            field=models.CharField(blank=True, help_text='031 $n – Armadura', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='incipitmusical',
            name='clave',
            field=models.CharField(blank=True, help_text='031 $g – Clave musical (ej.: G-2, F-4)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='incipitmusical',
            name='nota_general',
            field=models.TextField(blank=True, help_text='031 $q – Nota general', null=True),
        ),
        migrations.AddField(
            model_name='incipitmusical',
            name='nota_validez_codificada',
            field=models.CharField(blank=True, help_text='031 $s – Nota de validez codificada', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='incipitmusical',
            name='personaje',
            field=models.CharField(blank=True, help_text='031 $e – Personaje', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='incipitmusical',
            name='tiempo',
            field=models.CharField(blank=True, help_text='031 $o – Tiempo', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='incipitmusical',
            name='tonalidad_modo',
            field=models.CharField(blank=True, help_text='031 $r – Tonalidad o modo (ej.: g, C mayor)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='incipitmusical',
            name='notacion_musical',
            field=models.TextField(blank=True, help_text='031 $p – Íncipit musical codificado en PAE (Plaine & Easie)', null=True),
        ),
        migrations.AlterField(
            model_name='incipitmusical',
            name='numero_movimiento',
            field=models.PositiveIntegerField(default=1, help_text='031 $b – Número del movimiento (predeterminado: 1)'),
        ),
        migrations.AlterField(
            model_name='incipitmusical',
            name='numero_obra',
            field=models.PositiveIntegerField(default=1, help_text='031 $a – Número de la obra (predeterminado: 1)'),
        ),
        migrations.AlterField(
            model_name='incipitmusical',
            name='numero_pasaje',
            field=models.PositiveIntegerField(default=1, help_text='031 $c – Número de pasaje o sistema (predeterminado: 1)'),
        ),
        migrations.AlterField(
            model_name='incipitmusical',
            name='titulo_encabezamiento',
            field=models.CharField(blank=True, help_text='031 $d – Nombre del tempo o movimiento (ej: Aria, Allegro, Andante)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='incipitmusical',
            name='voz_instrumento',
            field=models.CharField(blank=True, default='piano', help_text='031 $m – Voz/instrumento', max_length=100, null=True),
        ),
    ]
