# Generated by Django 5.2.7 on 2025-10-31 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0002_remove_obrageneral_fecha_publicacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obrageneral',
            name='fecha_produccion_264',
        ),
        migrations.RemoveField(
            model_name='obrageneral',
            name='lugar_produccion_264',
        ),
        migrations.RemoveField(
            model_name='obrageneral',
            name='nombre_productor_264',
        ),
        migrations.CreateModel(
            name='ProduccionPublicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(blank=True, help_text='264 $a – Lugar de producción, publicación, distribución o fabricación', max_length=200, null=True)),
                ('nombre_entidad', models.CharField(blank=True, help_text='264 $b – Nombre del productor, editor, distribuidor o fabricante', max_length=200, null=True)),
                ('fecha', models.CharField(blank=True, help_text='264 $c – Fecha de producción, publicación, distribución, fabricación o copyright', max_length=100, null=True)),
                ('funcion', models.CharField(choices=[('0', 'Producción'), ('1', 'Publicación'), ('2', 'Distribución'), ('3', 'Fabricación'), ('4', 'Copyright')], default='0', help_text='Segundo indicador: función de la entidad (0=Producción para manuscritos)', max_length=1)),
                ('orden', models.PositiveIntegerField(default=1, help_text='Orden de aparición en el registro MARC')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(help_text='Obra a la que pertenece este registro 264', on_delete=django.db.models.deletion.CASCADE, related_name='produccion_publicacion', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': 'Producción/Publicación (264)',
                'verbose_name_plural': 'Producciones/Publicaciones (264)',
                'ordering': ['obra', 'orden'],
            },
        ),
    ]
