# Generated by Django 5.2.7 on 2025-11-16 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0002_alter_materia650_options_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='obrageneral',
            new_name='catalogacio_num_con_24e3b6_idx',
            old_name='marc_obra_g_num_con_dd27ed_idx',
        ),
        migrations.RenameIndex(
            model_name='obrageneral',
            new_name='catalogacio_tipo_re_8a21ab_idx',
            old_name='marc_obra_g_tipo_re_b04136_idx',
        ),
        migrations.RenameIndex(
            model_name='obrageneral',
            new_name='catalogacio_nivel_b_00223e_idx',
            old_name='marc_obra_g_nivel_b_f5550e_idx',
        ),
        migrations.RenameIndex(
            model_name='obrageneral',
            new_name='catalogacio_tipo_re_b50116_idx',
            old_name='marc_obra_g_tipo_re_b4c023_idx',
        ),
        migrations.RenameIndex(
            model_name='obrageneral',
            new_name='catalogacio_fecha_c_2cc522_idx',
            old_name='marc_obra_g_fecha_c_b02c98_idx',
        ),
        migrations.RenameIndex(
            model_name='obrageneral',
            new_name='catalogacio_titulo__a0d8a2_idx',
            old_name='marc_obra_g_titulo__df611c_idx',
        ),
        migrations.AlterModelTable(
            name='obrageneral',
            table='catalogacion_obra_general',
        ),
    ]
