# Generated by Django 5.2.7 on 2025-10-31 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0003_remove_obrageneral_fecha_produccion_264_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obrageneral',
            name='nombre_parte_245',
        ),
        migrations.RemoveField(
            model_name='obrageneral',
            name='numero_parte_245',
        ),
        migrations.RemoveField(
            model_name='obrageneral',
            name='presentacion_musical',
        ),
        migrations.RemoveField(
            model_name='obrageneral',
            name='resto_titulo',
        ),
        migrations.RemoveField(
            model_name='obrageneral',
            name='resto_titulo_variante',
        ),
        migrations.RemoveField(
            model_name='obrageneral',
            name='titulo_variante',
        ),
        migrations.AddField(
            model_name='obrageneral',
            name='subtitulo',
            field=models.CharField(blank=True, help_text='245 $b – Subtítulo', max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='Edicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edicion', models.CharField(help_text='250 $a – Edición', max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(help_text='Obra a la que pertenece esta edición', on_delete=django.db.models.deletion.CASCADE, related_name='ediciones', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': 'Edición (250)',
                'verbose_name_plural': 'Ediciones (250)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TituloAlternativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='246 $a – Título abreviado o alternativo', max_length=500)),
                ('resto_titulo', models.CharField(blank=True, help_text='246 $b – Resto del título variante', max_length=500, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(help_text='Obra a la que pertenece este título alternativo', on_delete=django.db.models.deletion.CASCADE, related_name='titulos_alternativos', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': 'Título Alternativo (246)',
                'verbose_name_plural': 'Títulos Alternativos (246)',
                'ordering': ['obra', 'id'],
            },
        ),
    ]
