# Generated by Django 5.2.7 on 2025-11-16 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0003_rename_marc_obra_g_num_con_dd27ed_idx_catalogacio_num_con_24e3b6_idx_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obrageneral',
            name='compositor_coleccion_773a',
        ),
        migrations.RemoveField(
            model_name='obrageneral',
            name='coordenadas_biograficas_700d',
        ),
        migrations.RemoveField(
            model_name='obrageneral',
            name='encabezamiento_principal_787a',
        ),
        migrations.RemoveField(
            model_name='obrageneral',
            name='enlace_unidad_774',
        ),
        migrations.RemoveField(
            model_name='obrageneral',
            name='entidad_relacionada_710a',
        ),
        migrations.RemoveField(
            model_name='obrageneral',
            name='materia_genero_655',
        ),
        migrations.RemoveField(
            model_name='obrageneral',
            name='materia_principal_650',
        ),
        migrations.RemoveField(
            model_name='obrageneral',
            name='nombre_relacionado_700a',
        ),
        migrations.RemoveField(
            model_name='obrageneral',
            name='sumario_520',
        ),
        migrations.RemoveField(
            model_name='obrageneral',
            name='titulo_coleccion_773t',
        ),
        migrations.RemoveField(
            model_name='obrageneral',
            name='titulo_obra_relacionada_787t',
        ),
        migrations.RemoveField(
            model_name='obrageneral',
            name='titulo_relacionado_700t',
        ),
        migrations.RemoveField(
            model_name='obrageneral',
            name='titulo_unidad_774t',
        ),
        migrations.AddField(
            model_name='obrageneral',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, help_text='Indica si el registro está activo o eliminado lógicamente'),
        ),
        migrations.AddField(
            model_name='obrageneral',
            name='eliminado_por',
            field=models.CharField(blank=True, help_text='Usuario que eliminó el registro', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='obrageneral',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se eliminó lógicamente el registro', null=True),
        ),
        migrations.CreateModel(
            name='EncabezamientoEnlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(help_text='ID de la autoridad')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(help_text='Tipo de autoridad (Persona, Título Uniforme o Entidad)', limit_choices_to={'model__in': ('autoridadpersona', 'autoridadtitulouniforme', 'autoridadentidad')}, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Encabezamiento de Enlace',
                'verbose_name_plural': 'Encabezamientos de Enlaces',
            },
        ),
        migrations.AlterField(
            model_name='enlacedocumentofuente773',
            name='encabezamiento_principal',
            field=models.ForeignKey(help_text='773 $a – Encabezamiento principal (Persona, Título o Entidad)', on_delete=django.db.models.deletion.PROTECT, to='catalogacion.encabezamientoenlace'),
        ),
        migrations.AlterField(
            model_name='enlaceunidadconstituyente774',
            name='encabezamiento_principal',
            field=models.ForeignKey(help_text='774 $a – Encabezamiento principal (Persona, Título o Entidad)', on_delete=django.db.models.deletion.PROTECT, to='catalogacion.encabezamientoenlace'),
        ),
        migrations.AlterField(
            model_name='otrasrelaciones787',
            name='encabezamiento_principal',
            field=models.ForeignKey(help_text='787 $a – Encabezamiento principal (Persona, Título o Entidad)', on_delete=django.db.models.deletion.PROTECT, to='catalogacion.encabezamientoenlace'),
        ),
        migrations.CreateModel(
            name='HistorialCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('accion', models.CharField(choices=[('create', 'Creación'), ('update', 'Modificación'), ('delete', 'Eliminación'), ('restore', 'Restauración')], help_text='Tipo de acción realizada', max_length=20)),
                ('usuario', models.CharField(help_text='Usuario que realizó el cambio', max_length=150)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora del cambio')),
                ('campos_modificados', models.JSONField(blank=True, help_text='Diccionario con los campos modificados {campo: {anterior: valor, nuevo: valor}}', null=True)),
                ('valores_completos', models.JSONField(blank=True, help_text='Snapshot completo del objeto después del cambio', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Dirección IP desde donde se hizo el cambio', null=True)),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre el cambio')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Historial de Cambio',
                'verbose_name_plural': 'Historial de Cambios',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='ObraLengua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Orden de aparición del idioma')),
                ('tipo_lengua', models.CharField(choices=[('a', 'Lengua del texto'), ('d', 'Lengua del resumen'), ('h', 'Lengua del original')], default='a', help_text='041 subcampo — Tipo de lengua', max_length=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('lengua', models.ForeignKey(help_text='041 $a — Código de lengua del texto/sonido', on_delete=django.db.models.deletion.PROTECT, to='catalogacion.codigolengua')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lenguas_obra', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': 'Lengua de la Obra (041)',
                'verbose_name_plural': 'Lenguas de la Obra (041)',
                'ordering': ['obra', 'orden'],
            },
        ),
        migrations.AddIndex(
            model_name='encabezamientoenlace',
            index=models.Index(fields=['content_type', 'object_id'], name='catalogacio_content_6f52e4_idx'),
        ),
        migrations.AddIndex(
            model_name='historialcambio',
            index=models.Index(fields=['content_type', 'object_id'], name='catalogacio_content_c53b36_idx'),
        ),
        migrations.AddIndex(
            model_name='historialcambio',
            index=models.Index(fields=['-fecha_cambio'], name='catalogacio_fecha_c_31c221_idx'),
        ),
        migrations.AddIndex(
            model_name='historialcambio',
            index=models.Index(fields=['usuario'], name='catalogacio_usuario_c9fda0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='obralengua',
            unique_together={('obra', 'lengua', 'tipo_lengua')},
        ),
    ]
