# Generated by Django 5.2.8 on 2026-02-01 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0003_expandir_codigos_pais_y_manuscrito_digital'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubdivisionCronologica650',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdivision', models.CharField(help_text='650 $z — Subdivisión cronológica (R)', max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('materia650', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdivisiones_cronologicas', to='catalogacion.materia650')),
            ],
            options={
                'verbose_name': '650 $z — Subdivisión cronológica',
                'verbose_name_plural': '650 $z — Subdivisiones cronológicas (R)',
                'ordering': ['materia650', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SubdivisionCronologica655',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdivision', models.CharField(help_text='655 $z — Subdivisión cronológica (R)', max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('materia655', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdivisiones_cronologicas', to='catalogacion.materiagenero655')),
            ],
            options={
                'verbose_name': '655 $z — Subdivisión cronológica',
                'verbose_name_plural': '655 $z — Subdivisiones cronológicas (R)',
                'ordering': ['materia655', 'id'],
            },
        ),
    ]
