# Generated by Django 5.2.7 on 2025-11-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0003_incipitmusical_armadura_incipitmusical_clave_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incipitmusical',
            name='nota_general',
        ),
        migrations.RemoveField(
            model_name='incipitmusical',
            name='nota_validez_codificada',
        ),
        migrations.RemoveField(
            model_name='incipitmusical',
            name='tonalidad_modo',
        ),
        migrations.AlterField(
            model_name='incipitmusical',
            name='armadura',
            field=models.CharField(blank=True, default=1, help_text='031 $n – Armadura', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incipitmusical',
            name='clave',
            field=models.CharField(blank=True, default=1, help_text='031 $g – Clave musical (ej.: G-2, F-4)', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incipitmusical',
            name='tiempo',
            field=models.CharField(blank=True, default=1, help_text='031 $o – Tiempo', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incipitmusical',
            name='titulo_encabezamiento',
            field=models.CharField(blank=True, default=1, help_text='031 $d – Nombre del tempo o movimiento (ej: Aria, Allegro, Andante)', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incipitmusical',
            name='voz_instrumento',
            field=models.CharField(blank=True, default='piano', help_text='031 $m – Voz/instrumento', max_length=100),
        ),
    ]
