# Generated by Django 5.2.7 on 2025-11-16 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0004_remove_obrageneral_compositor_coleccion_773a_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disponible856',
            name='texto_enlace',
        ),
        migrations.RemoveField(
            model_name='disponible856',
            name='url',
        ),
        migrations.CreateModel(
            name='TextoEnlace856',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_enlace', models.CharField(help_text='856 $y – Texto del enlace', max_length=255)),
                ('disponible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textos_enlace_856', to='catalogacion.disponible856')),
            ],
            options={
                'verbose_name': '856 $y – Texto del enlace',
                'verbose_name_plural': '📝 856 $y – Textos de enlaces',
            },
        ),
        migrations.CreateModel(
            name='URL856',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='856 $u – URL del recurso disponible', max_length=500)),
                ('disponible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls_856', to='catalogacion.disponible856')),
            ],
            options={
                'verbose_name': '856 $u – URL',
                'verbose_name_plural': '🔗 856 $u – URLs',
            },
        ),
    ]
