# Generated by Django 5.2.8 on 2026-02-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0004_agregar_subdivision_cronologica_650_655'),
    ]

    operations = [
        migrations.AddField(
            model_name='obrageneral',
            name='fecha_publicacion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se publicó la obra', null=True),
        ),
        migrations.AddField(
            model_name='obrageneral',
            name='publicada',
            field=models.BooleanField(db_index=True, default=False, help_text='Indica si la obra está publicada en el catálogo público'),
        ),
    ]
