# Generated by Django 5.2.8 on 2025-12-17 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0004_borradorobra_obra_objetivo'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='borradorobra',
            new_name='catalogacio_obra_ob_adb7d0_idx',
            old_name='catalogacio_obra_ob_3f5c4f_idx',
        ),
    ]
