# Generated by Django 5.2.7 on 2025-10-31 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0004_remove_obrageneral_nombre_parte_245_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obrageneral',
            name='dimensiones',
        ),
        migrations.RemoveField(
            model_name='obrageneral',
            name='extension',
        ),
        migrations.RemoveField(
            model_name='obrageneral',
            name='material_acompanante',
        ),
        migrations.RemoveField(
            model_name='obrageneral',
            name='otros_detalles_fisicos',
        ),
        migrations.CreateModel(
            name='DescripcionFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(help_text='300 $a – Extensión (ej: 1 partitura (24 p.))', max_length=200)),
                ('otras_caracteristicas_fisicas', models.CharField(blank=True, help_text='300 $b – Otras características físicas (ej: ilustraciones, notas)', max_length=200, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(help_text='Obra a la que pertenece esta descripción física', on_delete=django.db.models.deletion.CASCADE, related_name='descripciones_fisicas', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': 'Descripción Física (300)',
                'verbose_name_plural': 'Descripciones Físicas (300)',
                'ordering': ['obra', 'id'],
            },
        ),
    ]
