# Generated by Django 5.2.7 on 2025-10-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0005_remove_obrageneral_dimensiones_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produccionpublicacion',
            options={'ordering': ['obra', 'id'], 'verbose_name': 'Producción/Publicación (264)', 'verbose_name_plural': 'Producciones/Publicaciones (264)'},
        ),
        migrations.RemoveField(
            model_name='produccionpublicacion',
            name='orden',
        ),
        migrations.AddField(
            model_name='descripcionfisica',
            name='dimensiones',
            field=models.CharField(blank=True, help_text='300 $c – Dimensiones (ej: 30 cm)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='descripcionfisica',
            name='material_acompanante',
            field=models.CharField(blank=True, help_text='300 $e – Material acompañante (ej: 1 CD)', max_length=200, null=True),
        ),
    ]
