# Generated by Django 5.2.8 on 2026-02-04 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0005_add_publicacion_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subdivisioncronologica650',
            options={'ordering': ['materia650', 'id'], 'verbose_name': '650 $z — Subdivisión geográfica', 'verbose_name_plural': '650 $z — Subdivisiones geográficas (R)'},
        ),
        migrations.AlterModelOptions(
            name='subdivisionmateria650',
            options={'ordering': ['materia650', 'id'], 'verbose_name': '650 $y — Subdivisión cronológica', 'verbose_name_plural': '650 $y — Subdivisión cronológica (R)'},
        ),
        migrations.AlterField(
            model_name='subdivisioncronologica650',
            name='materia650',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdivisiones_geograficas', to='catalogacion.materia650'),
        ),
        migrations.AlterField(
            model_name='subdivisioncronologica650',
            name='subdivision',
            field=models.CharField(help_text='650 $z — Subdivisión geográfica (R)', max_length=200),
        ),
        migrations.AlterField(
            model_name='subdivisionmateria650',
            name='subdivision',
            field=models.CharField(help_text='650 $y — Subdivisión cronológica  (R)', max_length=200),
        ),
    ]
