# Generated by Django 5.2.7 on 2025-12-02 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0006_titulos_uniformes_enlaces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obrageneral',
            name='arreglo_130',
            field=models.CharField(blank=True, choices=[('arreglo', 'Arreglo')], default='arreglo', help_text='130 $o — Arreglo (predeterminado: Arreglo)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='obrageneral',
            name='arreglo_240',
            field=models.CharField(blank=True, choices=[('arreglo', 'Arreglo')], default='arreglo', help_text='240 $o — Arreglo (predeterminado: Arreglo)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='obrageneral',
            name='control_nota_028',
            field=models.CharField(blank=True, choices=[('0', 'No hay nota ni punto de acceso adicional'), ('1', 'Nota, hay punto de acceso adicional'), ('2', 'Nota, no hay punto de acceso adicional'), ('3', 'No hay nota, hay punto de acceso adicional')], default='0', help_text='028 Segundo indicador — Control de nota (predeterminado: No hay nota ni punto de acceso adicional)', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='obrageneral',
            name='medio_interpretacion_130',
            field=models.CharField(blank=True, choices=[('piano', 'Piano'), ('dos pianos', 'Dos pianos'), ('piano a cuatro manos', 'Piano a cuatro manos'), ('piano con acompañamiento', 'Piano con acompañamiento')], default='piano', help_text='130 $m — Medio de interpretación (predeterminado: piano)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='obrageneral',
            name='medio_interpretacion_240',
            field=models.CharField(blank=True, choices=[('piano', 'Piano'), ('dos pianos', 'Dos pianos'), ('piano a cuatro manos', 'Piano a cuatro manos'), ('piano con acompañamiento', 'Piano con acompañamiento')], default='piano', help_text='240 $m — Medio de interpretación (predeterminado: piano)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='obrageneral',
            name='tipo_numero_028',
            field=models.CharField(blank=True, choices=[('0', 'Número de publicación'), ('1', 'Número de matriz'), ('2', 'Número de plancha'), ('3', 'Otro número de música'), ('4', 'Número de videograbación'), ('5', 'Otro número de editor')], default='2', help_text='028 Primer indicador — Tipo de número de editor (predeterminado: Número de plancha)', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='produccionpublicacion',
            name='funcion',
            field=models.CharField(choices=[('0', 'Producción'), ('1', 'Publicación'), ('2', 'Distribución'), ('3', 'Fabricación'), ('4', 'Copyright')], default='0', help_text='264 segundo indicador – Función de la entidad (predeterminado: Producción para manuscritos)', max_length=1),
        ),
    ]
