# Generated by Django 5.2.7 on 2025-11-01 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0006_alter_produccionpublicacion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtribucionCompositor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atribucion', models.CharField(choices=[('atribuida', 'Atribuida'), ('certificada', 'Certificada'), ('erronea', 'Erronea')], default='certificada', help_text='100 $j – Calificador de atribución (predeterminado: certificada)', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Atribución Compositor (100 $j)',
                'verbose_name_plural': 'Atribuciones Compositor (100 $j - R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CaracteristicaMusicaNotada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Característica Música Notada (348)',
                'verbose_name_plural': 'Características Música Notada (348 - R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CodigoLengua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicacion_traduccion', models.CharField(choices=[('#', 'No se proporciona información'), ('0', 'El documento no es ni incluye una traducción'), ('1', 'El documento es o incluye una traducción')], default='0', help_text='Primer indicador: ¿Es traducción?', max_length=1)),
                ('fuente_codigo', models.CharField(choices=[('#', 'Código MARC de lengua'), ('7', 'Fuente especificada en el subcampo $2')], default='#', help_text='Segundo indicador: Fuente del código', max_length=1)),
                ('fuente_especificada', models.CharField(blank=True, help_text='041 $2 – Fuente del código (solo si segundo indicador es 7)', max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Código de Lengua (041)',
                'verbose_name_plural': 'Códigos de Lengua (041 - R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CodigoPaisEntidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_pais', models.CharField(choices=[('ar', 'Argentina'), ('bo', 'Bolivia'), ('br', 'Brasil'), ('cl', 'Chile'), ('co', 'Colombia'), ('cr', 'Costa Rica'), ('cu', 'Cuba'), ('ec', 'Ecuador'), ('sv', 'El Salvador'), ('gt', 'Guatemala'), ('ho', 'Honduras'), ('mx', 'México'), ('nq', 'Nicaragua'), ('pa', 'Panamá'), ('pe', 'Perú'), ('pr', 'Puerto Rico'), ('dr', 'República Dominicana'), ('uy', 'Uruguay'), ('ve', 'Venezuela')], default='ec', help_text='044 $a – Código ISO 3166-1 alfa-2 del país', max_length=2)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'País Editor/Productor (044 $a)',
                'verbose_name_plural': 'Países Editor/Productor (044 $a - R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DesignacionNumericaObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Designación Numérica (383)',
                'verbose_name_plural': 'Designaciones Numéricas (383 - R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Dimension300',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(help_text="300 $c – Dimensión (ej: '30 cm', '2.5 MB')", max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dimensión (300 $c)',
                'verbose_name_plural': 'Dimensiones (300 $c - R)',
                'ordering': ['descripcion_fisica', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Extension300',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(help_text="300 $a – Extensión (ej: '1 partitura (24 p.)')", max_length=500)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Extensión (300 $a)',
                'verbose_name_plural': 'Extensiones (300 $a - R)',
                'ordering': ['descripcion_fisica', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Forma130',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Forma (130 $k)',
                'verbose_name_plural': 'Formas (130 $k - R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Forma240',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma', models.CharField(choices=[('adaptación', 'Adaptación'), ('boceto', 'Boceto'), ('fragmento', 'Fragmento'), ('selección', 'Selección'), ('tema con variaciones', 'Tema con variaciones')], help_text='240 $k – Forma (cruzar con campo 655)', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Forma (240 $k)',
                'verbose_name_plural': 'Formas (240 $k - R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Formato348',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formato', models.CharField(choices=[('parte', 'Parte'), ('partitura', 'Partitura'), ('partitura de coro', 'Partitura de coro'), ('partitura piano vocal', 'Partitura piano-vocal')], help_text='348 $a – Formato de presentación (repetible dentro de cada 348)', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Formato (348 $a)',
                'verbose_name_plural': 'Formatos (348 $a - R)',
                'ordering': ['caracteristica', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FuncionCompositor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcion', models.CharField(choices=[('arreglista', 'Arreglista'), ('coeditor', 'Coeditor'), ('compilador', 'Compilador'), ('compositor', 'Compositor'), ('copista', 'Copista'), ('dedicatario', 'Dedicatario'), ('editor', 'Editor'), ('prologuista', 'Prologuista')], default='compositor', help_text='100 $e – Función del compositor (predeterminado: compositor)', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Función Compositor (100 $e)',
                'verbose_name_plural': 'Funciones Compositor (100 $e - R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IdiomaObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('ger', 'Alemán'), ('spa', 'Español'), ('fre', 'Francés'), ('eng', 'Inglés'), ('ita', 'Italiano'), ('por', 'Portugués')], default='spa', help_text='041 $a – Código ISO 639-2/B del idioma', max_length=3)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Idioma (041 $a)',
                'verbose_name_plural': 'Idiomas (041 $a - R)',
                'ordering': ['codigo_lengua', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IncipitMusical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_obra', models.PositiveIntegerField(default=1, help_text='031 $a – Número de la obra (predeterminado: 1)')),
                ('numero_movimiento', models.PositiveIntegerField(default=1, help_text='031 $b – Número del movimiento (predeterminado: 1)')),
                ('numero_pasaje', models.PositiveIntegerField(default=1, help_text='031 $c – Número de pasaje o sistema (predeterminado: 1)')),
                ('titulo_encabezamiento', models.CharField(blank=True, help_text='031 $d – Nombre del tempo o movimiento (ej: Aria, Allegro, Andante)', max_length=200, null=True)),
                ('voz_instrumento', models.CharField(blank=True, help_text='031 $m – Voz/instrumento (usar solo si NO es para piano)', max_length=100, null=True)),
                ('notacion_musical', models.TextField(blank=True, help_text='031 $p – Íncipit musical codificado (ej: Plaine & Easie, MusicXML, ABC)', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Íncipit Musical (031)',
                'verbose_name_plural': 'Íncipits Musicales (031 - R)',
                'ordering': ['obra', 'numero_obra', 'numero_movimiento', 'numero_pasaje'],
            },
        ),
        migrations.CreateModel(
            name='IncipitURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='031 $u – URL del íncipit codificado en base de datos externa', max_length=500)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'URL de Íncipit (031 $u)',
                'verbose_name_plural': 'URLs de Íncipit (031 $u - R)',
                'ordering': ['incipit', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ISBN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(help_text='020 $a – ISBN', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ISBN (020)',
                'verbose_name_plural': 'ISBN (020)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ISMN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismn', models.CharField(help_text='024 $a – ISMN', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ISMN (024)',
                'verbose_name_plural': 'ISMN (024)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MedioFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Medio Físico (340)',
                'verbose_name_plural': 'Medios Físicos (340 - R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MedioInterpretacion130',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medio', models.CharField(default='piano', help_text='130 $m – Medio de interpretación (predeterminado: piano)', max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Medio de Interpretación (130 $m)',
                'verbose_name_plural': 'Medios de Interpretación (130 $m - R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MedioInterpretacion240',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medio', models.CharField(default='piano', help_text='240 $m – Medio de interpretación (predeterminado: piano)', max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Medio de Interpretación (240 $m)',
                'verbose_name_plural': 'Medios de Interpretación (240 $m - R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MedioInterpretacion382',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Medio de Interpretación (382)',
                'verbose_name_plural': 'Medios de Interpretación (382 - R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MedioInterpretacion382_a',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medio', models.CharField(choices=[('piano', 'Piano'), ('dos pianos', 'Dos pianos'), ('piano a cuatro manos', 'Piano a cuatro manos'), ('piano con acompañamiento', 'Piano con acompañamiento')], default='piano', help_text='382 $a – Medio de interpretación (predeterminado: piano)', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Medio (382 $a)',
                'verbose_name_plural': 'Medios (382 $a - R)',
                'ordering': ['medio_interpretacion', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MencionSerie490',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relacion', models.CharField(choices=[('0', 'No relacionado (sin entrada secundaria)'), ('1', 'Relacionado (con entrada secundaria 800-830)')], default='0', help_text='490 primer indicador – Relación: 0=no relacionado, 1=relacionado con 800-830', max_length=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mención de Serie (490)',
                'verbose_name_plural': 'Menciones de Serie (490 - R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NombreParteSección130',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='130 $p – Nombre de parte/sección (ej: Allegro, Andante, Finale)', max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nombre de Parte/Sección (130 $p)',
                'verbose_name_plural': 'Nombres de Parte/Sección (130 $p - R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NombreParteSección240',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='240 $p – Nombre de parte/sección (ej: Allegro, Andante, Finale)', max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nombre de Parte/Sección (240 $p)',
                'verbose_name_plural': 'Nombres de Parte/Sección (240 $p - R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NumeroEditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='028 $a – Número de editor, plancha, placa o código distintivo', max_length=100)),
                ('tipo_numero', models.CharField(choices=[('0', 'Número de publicación'), ('1', 'Número de matriz'), ('2', 'Número de plancha'), ('3', 'Otro número de música'), ('4', 'Número de videograbación'), ('5', 'Otro número de editor')], default='2', help_text='Primer indicador: Tipo de número de editor', max_length=1)),
                ('control_nota', models.CharField(choices=[('0', 'No hay nota ni punto de acceso adicional'), ('1', 'Nota, hay punto de acceso adicional'), ('2', 'Nota, no hay punto de acceso adicional'), ('3', 'No hay nota, hay punto de acceso adicional')], default='0', help_text='Segundo indicador: Control de nota/punto de acceso adicional', max_length=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Número de Editor (028)',
                'verbose_name_plural': 'Números de Editor (028 - R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NumeroInterpretes382',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text='382 $n – Número de intérpretes de un mismo medio (ej: 2, 4, 8)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Número Intérpretes (382 $n)',
                'verbose_name_plural': 'Números Intérpretes (382 $n - R)',
                'ordering': ['medio_interpretacion', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NumeroObra383',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_obra', models.CharField(help_text="383 $a – Número de obra (ej: '1', '2', 'K. 545', 'BWV 1001', ", max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Número de Obra (383 $a)',
                'verbose_name_plural': 'Números de Obra (383 $a - R)',
                'ordering': ['designacion_numerica', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NumeroParteSección130',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='130 $n – Número de parte/sección (ej: I, II, III o 1, 2, 3)', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Número de Parte/Sección (130 $n)',
                'verbose_name_plural': 'Números de Parte/Sección (130 $n - R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NumeroParteSección240',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='240 $n – Número de parte/sección (ej: I, II, III o 1, 2, 3)', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Número de Parte/Sección (240 $n)',
                'verbose_name_plural': 'Números de Parte/Sección (240 $n - R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Opus383',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opus', models.CharField(help_text="383 $b – Número de Opus (ej: 'Op. 27, No. 2', 'Op. 131')", max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Opus (383 $b)',
                'verbose_name_plural': 'Opus (383 $b - R)',
                'ordering': ['designacion_numerica', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Solista382',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solista', models.CharField(choices=[('piano', 'Piano')], default='piano', help_text='382 $b – Solista (predeterminado: piano)', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Solista (382 $b)',
                'verbose_name_plural': 'Solistas (382 $b - R)',
                'ordering': ['medio_interpretacion', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Tecnica340',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecnica', models.CharField(choices=[('autógrafo', 'Autógrafo'), ('posible autógrafo', 'Posible autógrafo'), ('manuscrito', 'Manuscrito'), ('manuscrito de copista no identificado', 'Manuscrito de copista no identificado'), ('impreso', 'Impreso'), ('fotocopia de manuscrito', 'Fotocopia de manuscrito'), ('fotocopia de impreso', 'Fotocopia de impreso')], help_text='340 $d – Técnica de registro (repetible dentro de cada 340)', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Técnica (340 $d)',
                'verbose_name_plural': 'Técnicas (340 $d - R)',
                'ordering': ['medio_fisico', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TituloSerie490',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_serie', models.CharField(help_text="490 $a – Título/mención de la serie (ej: 'Colección Támesis. Serie A')", max_length=300)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Título Serie (490 $a)',
                'verbose_name_plural': 'Títulos Serie (490 $a - R)',
                'ordering': ['mencion_serie', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VolumenSerie490',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volumen', models.CharField(help_text="490 $v – Designación de volumen (ej: '260', 'Vol. 5', 'Tomo III')", max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Volumen (490 $v)',
                'verbose_name_plural': 'Volúmenes (490 $v - R)',
                'ordering': ['mencion_serie', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='descripcionfisica',
            options={'ordering': ['obra', 'id'], 'verbose_name': 'Descripción Física (300)', 'verbose_name_plural': 'Descripciones Físicas (300 - R)'},
        ),
        migrations.AlterModelOptions(
            name='edicion',
            options={'ordering': ['obra', 'id'], 'verbose_name': 'Edición (250)', 'verbose_name_plural': 'Ediciones (250 - R)'},
        ),
        migrations.AlterModelOptions(
            name='obrageneral',
            options={'ordering': ['-num_control'], 'verbose_name': 'Obra Musical MARC21', 'verbose_name_plural': 'Obras Musicales MARC21'},
        ),
        migrations.AlterModelOptions(
            name='produccionpublicacion',
            options={'ordering': ['obra', 'id'], 'verbose_name': 'Producción/Publicación (264)', 'verbose_name_plural': 'Producciones/Publicaciones (264 - R)'},
        ),
        migrations.RemoveField(
            model_name='descripcionfisica',
            name='dimensiones',
        ),
        migrations.RemoveField(
            model_name='descripcionfisica',
            name='extension',
        ),
        migrations.RemoveField(
            model_name='obrageneral',
            name='codigo_lengua',
        ),
        migrations.RemoveField(
            model_name='obrageneral',
            name='codigo_pais',
        ),
        migrations.RemoveField(
            model_name='obrageneral',
            name='compositor_autoria',
        ),
        migrations.RemoveField(
            model_name='obrageneral',
            name='compositor_funcion',
        ),
        migrations.RemoveField(
            model_name='obrageneral',
            name='incipit_notacion',
        ),
        migrations.RemoveField(
            model_name='obrageneral',
            name='incipit_num_movimiento',
        ),
        migrations.RemoveField(
            model_name='obrageneral',
            name='incipit_num_obra',
        ),
        migrations.RemoveField(
            model_name='obrageneral',
            name='incipit_num_pasaje',
        ),
        migrations.RemoveField(
            model_name='obrageneral',
            name='incipit_titulo',
        ),
        migrations.RemoveField(
            model_name='obrageneral',
            name='incipit_url',
        ),
        migrations.RemoveField(
            model_name='obrageneral',
            name='incipit_voz_instrumento',
        ),
        migrations.RemoveField(
            model_name='obrageneral',
            name='indicador_028',
        ),
        migrations.RemoveField(
            model_name='obrageneral',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='obrageneral',
            name='ismn',
        ),
        migrations.RemoveField(
            model_name='obrageneral',
            name='numero_editor',
        ),
        migrations.RemoveField(
            model_name='obrageneral',
            name='titulo_240_forma',
        ),
        migrations.RemoveField(
            model_name='obrageneral',
            name='titulo_240_medio_interpretacion',
        ),
        migrations.RemoveField(
            model_name='obrageneral',
            name='titulo_240_nombre_parte',
        ),
        migrations.RemoveField(
            model_name='obrageneral',
            name='titulo_240_num_parte',
        ),
        migrations.RemoveField(
            model_name='obrageneral',
            name='titulo_uniforme_forma',
        ),
        migrations.RemoveField(
            model_name='obrageneral',
            name='titulo_uniforme_medio_interpretacion',
        ),
        migrations.RemoveField(
            model_name='obrageneral',
            name='titulo_uniforme_nombre_parte',
        ),
        migrations.RemoveField(
            model_name='obrageneral',
            name='titulo_uniforme_num_parte',
        ),
        migrations.AddField(
            model_name='descripcionfisica',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='edicion',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='obrageneral',
            name='tonalidad_384',
            field=models.CharField(blank=True, choices=[('Do mayor', 'Do mayor'), ('Do# mayor', 'Do# mayor'), ('Reb mayor', 'Re♭ mayor'), ('Re mayor', 'Re mayor'), ('Mib mayor', 'Mi♭ mayor'), ('Mi mayor', 'Mi mayor'), ('Fa mayor', 'Fa mayor'), ('Fa# mayor', 'Fa# mayor'), ('Sol mayor', 'Sol mayor'), ('Sol# mayor', 'Sol# mayor'), ('Lab mayor', 'La♭ mayor'), ('La mayor', 'La mayor'), ('Sib mayor', 'Si♭ mayor'), ('Si mayor', 'Si mayor'), ('Do menor', 'Do menor'), ('Do# menor', 'Do# menor'), ('Reb menor', 'Re♭ menor'), ('Re menor', 'Re menor'), ('Mib menor', 'Mi♭ menor'), ('Mi menor', 'Mi menor'), ('Fa menor', 'Fa menor'), ('Fa# menor', 'Fa# menor'), ('Sol menor', 'Sol menor'), ('Sol# menor', 'Sol# menor'), ('Lab menor', 'La♭ menor'), ('La menor', 'La menor'), ('Sib menor', 'Si♭ menor'), ('Si menor', 'Si menor')], help_text='384 $a – Tonalidad (NR)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='produccionpublicacion',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='descripcionfisica',
            name='material_acompanante',
            field=models.CharField(blank=True, help_text='300 $e – Material acompañante (NR)', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='descripcionfisica',
            name='obra',
            field=models.ForeignKey(help_text='Obra a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='descripciones_fisicas', to='catalogacion.obrageneral'),
        ),
        migrations.AlterField(
            model_name='descripcionfisica',
            name='otras_caracteristicas_fisicas',
            field=models.CharField(blank=True, help_text='300 $b – Otras características físicas (NR)', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='edicion',
            name='edicion',
            field=models.CharField(help_text='250 $a – Edición', max_length=500),
        ),
        migrations.AlterField(
            model_name='obrageneral',
            name='clasif_institucion',
            field=models.CharField(default='UNL', editable=False, help_text='092 $a – Institución (duplica campo 040 $a)', max_length=10),
        ),
        migrations.AlterField(
            model_name='obrageneral',
            name='clasif_ms_imp',
            field=models.CharField(blank=True, choices=[('Ms', 'Manuscrito'), ('Imp', 'Impreso')], editable=False, help_text='092 $d – Ms (Manuscrito) o Imp (Impreso) - Cruza con posición 06 de cabecera', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='obrageneral',
            name='clasif_num_control',
            field=models.CharField(blank=True, editable=False, help_text='092 $0 – Número de control (duplica campo 001)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='obrageneral',
            name='clasif_pais',
            field=models.CharField(blank=True, editable=False, help_text='092 $c – País (duplica campo 044 $a)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='obrageneral',
            name='clasif_proyecto',
            field=models.CharField(default='BLMP', editable=False, help_text='092 $b – Proyecto', max_length=50),
        ),
        migrations.AlterField(
            model_name='obrageneral',
            name='titulo_240',
            field=models.ForeignKey(blank=True, help_text='240 $a – Título uniforme normalizado (cruzar con campo 130)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='obras_240', to='catalogacion.autoridadtitulouniforme'),
        ),
        migrations.AlterField(
            model_name='obrageneral',
            name='titulo_240_arreglo',
            field=models.CharField(blank=True, default='arreglo', help_text='240 $o – Arreglo (NR - No repetible, predeterminado: arreglo)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='obrageneral',
            name='titulo_240_tonalidad',
            field=models.CharField(blank=True, choices=[('Do mayor', 'Do mayor'), ('Do# mayor', 'Do# mayor'), ('Reb mayor', 'Re♭ mayor'), ('Re mayor', 'Re mayor'), ('Mib mayor', 'Mi♭ mayor'), ('Mi mayor', 'Mi mayor'), ('Fa mayor', 'Fa mayor'), ('Fa# mayor', 'Fa# mayor'), ('Sol mayor', 'Sol mayor'), ('Sol# mayor', 'Sol# mayor'), ('Lab mayor', 'La♭ mayor'), ('La mayor', 'La mayor'), ('Sib mayor', 'Si♭ mayor'), ('Si mayor', 'Si mayor'), ('Do menor', 'Do menor'), ('Do# menor', 'Do# menor'), ('Reb menor', 'Re♭ menor'), ('Re menor', 'Re menor'), ('Mib menor', 'Mi♭ menor'), ('Mi menor', 'Mi menor'), ('Fa menor', 'Fa menor'), ('Fa# menor', 'Fa# menor'), ('Sol menor', 'Sol menor'), ('Sol# menor', 'Sol# menor'), ('Lab menor', 'La♭ menor'), ('La menor', 'La menor'), ('Sib menor', 'Si♭ menor'), ('Si menor', 'Si menor')], help_text='240 $r – Tonalidad (NR - No repetible)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='obrageneral',
            name='titulo_uniforme',
            field=models.ForeignKey(blank=True, help_text='130 $a – Título uniforme normalizado (cruzar con campo 240)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='obras_130', to='catalogacion.autoridadtitulouniforme'),
        ),
        migrations.AlterField(
            model_name='obrageneral',
            name='titulo_uniforme_tonalidad',
            field=models.CharField(blank=True, choices=[('Do mayor', 'Do mayor'), ('Do# mayor', 'Do# mayor'), ('Reb mayor', 'Re♭ mayor'), ('Re mayor', 'Re mayor'), ('Mib mayor', 'Mi♭ mayor'), ('Mi mayor', 'Mi mayor'), ('Fa mayor', 'Fa mayor'), ('Fa# mayor', 'Fa# mayor'), ('Sol mayor', 'Sol mayor'), ('Sol# mayor', 'Sol# mayor'), ('Lab mayor', 'La♭ mayor'), ('La mayor', 'La mayor'), ('Sib mayor', 'Si♭ mayor'), ('Si mayor', 'Si mayor'), ('Do menor', 'Do menor'), ('Do# menor', 'Do# menor'), ('Reb menor', 'Re♭ menor'), ('Re menor', 'Re menor'), ('Mib menor', 'Mi♭ menor'), ('Mi menor', 'Mi menor'), ('Fa menor', 'Fa menor'), ('Fa# menor', 'Fa# menor'), ('Sol menor', 'Sol menor'), ('Sol# menor', 'Sol# menor'), ('Lab menor', 'La♭ menor'), ('La menor', 'La menor'), ('Sib menor', 'Si♭ menor'), ('Si menor', 'Si menor')], help_text='130 $r – Tonalidad (NR - No repetible)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='produccionpublicacion',
            name='fecha',
            field=models.CharField(blank=True, help_text='264 $c – Fecha de producción/publicación (R)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='produccionpublicacion',
            name='funcion',
            field=models.CharField(choices=[('0', 'Producción'), ('1', 'Publicación'), ('2', 'Distribución'), ('3', 'Fabricación'), ('4', 'Copyright')], default='0', help_text='264 segundo indicador – Función de la entidad', max_length=1),
        ),
        migrations.AlterField(
            model_name='produccionpublicacion',
            name='lugar',
            field=models.CharField(blank=True, help_text='264 $a – Lugar de producción/publicación (R)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='produccionpublicacion',
            name='nombre_entidad',
            field=models.CharField(blank=True, help_text='264 $b – Nombre del productor/editor/distribuidor (R)', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='produccionpublicacion',
            name='obra',
            field=models.ForeignKey(help_text='Obra a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='producciones_publicaciones', to='catalogacion.obrageneral'),
        ),
        migrations.AddIndex(
            model_name='obrageneral',
            index=models.Index(fields=['num_control'], name='catalogacio_num_con_5cfcb5_idx'),
        ),
        migrations.AddIndex(
            model_name='obrageneral',
            index=models.Index(fields=['tipo_registro'], name='catalogacio_tipo_re_aa2327_idx'),
        ),
        migrations.AddIndex(
            model_name='obrageneral',
            index=models.Index(fields=['nivel_bibliografico'], name='catalogacio_nivel_b_8e99cf_idx'),
        ),
        migrations.AddIndex(
            model_name='obrageneral',
            index=models.Index(fields=['-fecha_creacion_sistema'], name='catalogacio_fecha_c_1c88ca_idx'),
        ),
        migrations.AddField(
            model_name='atribucioncompositor',
            name='obra',
            field=models.ForeignKey(help_text='Obra a la que pertenece esta atribución', on_delete=django.db.models.deletion.CASCADE, related_name='atribuciones_compositor', to='catalogacion.obrageneral'),
        ),
        migrations.AddField(
            model_name='caracteristicamusicanotada',
            name='obra',
            field=models.ForeignKey(help_text='Obra a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='caracteristicas_musica_notada', to='catalogacion.obrageneral'),
        ),
        migrations.AddField(
            model_name='codigolengua',
            name='obra',
            field=models.ForeignKey(help_text='Obra a la que pertenece este código de lengua', on_delete=django.db.models.deletion.CASCADE, related_name='codigos_lengua', to='catalogacion.obrageneral'),
        ),
        migrations.AddField(
            model_name='codigopaisentidad',
            name='obra',
            field=models.ForeignKey(help_text='Obra a la que pertenece este código de país', on_delete=django.db.models.deletion.CASCADE, related_name='codigos_pais_entidad', to='catalogacion.obrageneral'),
        ),
        migrations.AddField(
            model_name='designacionnumericaobra',
            name='obra',
            field=models.ForeignKey(help_text='Obra a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='designaciones_numericas', to='catalogacion.obrageneral'),
        ),
        migrations.AddField(
            model_name='dimension300',
            name='descripcion_fisica',
            field=models.ForeignKey(help_text='Descripción física a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='dimensiones_set', to='catalogacion.descripcionfisica'),
        ),
        migrations.AddField(
            model_name='extension300',
            name='descripcion_fisica',
            field=models.ForeignKey(help_text='Descripción física a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='extensiones', to='catalogacion.descripcionfisica'),
        ),
        migrations.AddField(
            model_name='forma130',
            name='forma',
            field=models.ForeignKey(help_text='130 $k – Forma normalizada', on_delete=django.db.models.deletion.PROTECT, to='catalogacion.autoridadformamusical'),
        ),
        migrations.AddField(
            model_name='forma130',
            name='obra',
            field=models.ForeignKey(help_text='Obra a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='formas_130', to='catalogacion.obrageneral'),
        ),
        migrations.AddField(
            model_name='forma240',
            name='obra',
            field=models.ForeignKey(help_text='Obra a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='formas_240', to='catalogacion.obrageneral'),
        ),
        migrations.AddField(
            model_name='formato348',
            name='caracteristica',
            field=models.ForeignKey(help_text='Característica a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='formatos', to='catalogacion.caracteristicamusicanotada'),
        ),
        migrations.AddField(
            model_name='funcioncompositor',
            name='obra',
            field=models.ForeignKey(help_text='Obra a la que pertenece esta función', on_delete=django.db.models.deletion.CASCADE, related_name='funciones_compositor', to='catalogacion.obrageneral'),
        ),
        migrations.AddField(
            model_name='idiomaobra',
            name='codigo_lengua',
            field=models.ForeignKey(help_text='Registro 041 al que pertenece este idioma', on_delete=django.db.models.deletion.CASCADE, related_name='idiomas', to='catalogacion.codigolengua'),
        ),
        migrations.AddField(
            model_name='incipitmusical',
            name='obra',
            field=models.ForeignKey(help_text='Obra a la que pertenece este íncipit', on_delete=django.db.models.deletion.CASCADE, related_name='incipits_musicales', to='catalogacion.obrageneral'),
        ),
        migrations.AddField(
            model_name='incipiturl',
            name='incipit',
            field=models.ForeignKey(help_text='Íncipit al que pertenece esta URL', on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='catalogacion.incipitmusical'),
        ),
        migrations.AddField(
            model_name='isbn',
            name='obra',
            field=models.ForeignKey(help_text='Obra a la que pertenece este ISBN', on_delete=django.db.models.deletion.CASCADE, related_name='isbns', to='catalogacion.obrageneral'),
        ),
        migrations.AddField(
            model_name='ismn',
            name='obra',
            field=models.ForeignKey(help_text='Obra a la que pertenece este ISMN', on_delete=django.db.models.deletion.CASCADE, related_name='ismns', to='catalogacion.obrageneral'),
        ),
        migrations.AddField(
            model_name='mediofisico',
            name='obra',
            field=models.ForeignKey(help_text='Obra a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='medios_fisicos', to='catalogacion.obrageneral'),
        ),
        migrations.AddField(
            model_name='mediointerpretacion130',
            name='obra',
            field=models.ForeignKey(help_text='Obra a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='medios_interpretacion_130', to='catalogacion.obrageneral'),
        ),
        migrations.AddField(
            model_name='mediointerpretacion240',
            name='obra',
            field=models.ForeignKey(help_text='Obra a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='medios_interpretacion_240', to='catalogacion.obrageneral'),
        ),
        migrations.AddField(
            model_name='mediointerpretacion382',
            name='obra',
            field=models.ForeignKey(help_text='Obra a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='medios_interpretacion_382', to='catalogacion.obrageneral'),
        ),
        migrations.AddField(
            model_name='mediointerpretacion382_a',
            name='medio_interpretacion',
            field=models.ForeignKey(help_text='Medio de interpretación al que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='medios', to='catalogacion.mediointerpretacion382'),
        ),
        migrations.AddField(
            model_name='mencionserie490',
            name='obra',
            field=models.ForeignKey(help_text='Obra a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='menciones_serie', to='catalogacion.obrageneral'),
        ),
        migrations.AddField(
            model_name='nombrepartesección130',
            name='obra',
            field=models.ForeignKey(help_text='Obra a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='nombres_parte_130', to='catalogacion.obrageneral'),
        ),
        migrations.AddField(
            model_name='nombrepartesección240',
            name='obra',
            field=models.ForeignKey(help_text='Obra a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='nombres_parte_240', to='catalogacion.obrageneral'),
        ),
        migrations.AddField(
            model_name='numeroeditor',
            name='obra',
            field=models.ForeignKey(help_text='Obra a la que pertenece este número de editor', on_delete=django.db.models.deletion.CASCADE, related_name='numeros_editor', to='catalogacion.obrageneral'),
        ),
        migrations.AddField(
            model_name='numerointerpretes382',
            name='medio_interpretacion',
            field=models.ForeignKey(help_text='Medio de interpretación al que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='numeros_interpretes', to='catalogacion.mediointerpretacion382'),
        ),
        migrations.AddField(
            model_name='numeroobra383',
            name='designacion_numerica',
            field=models.ForeignKey(help_text='Designación a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='numeros_obra', to='catalogacion.designacionnumericaobra'),
        ),
        migrations.AddField(
            model_name='numeropartesección130',
            name='obra',
            field=models.ForeignKey(help_text='Obra a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='numeros_parte_130', to='catalogacion.obrageneral'),
        ),
        migrations.AddField(
            model_name='numeropartesección240',
            name='obra',
            field=models.ForeignKey(help_text='Obra a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='numeros_parte_240', to='catalogacion.obrageneral'),
        ),
        migrations.AddField(
            model_name='opus383',
            name='designacion_numerica',
            field=models.ForeignKey(help_text='Designación a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='opus', to='catalogacion.designacionnumericaobra'),
        ),
        migrations.AddField(
            model_name='solista382',
            name='medio_interpretacion',
            field=models.ForeignKey(help_text='Medio de interpretación al que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='solistas', to='catalogacion.mediointerpretacion382'),
        ),
        migrations.AddField(
            model_name='tecnica340',
            name='medio_fisico',
            field=models.ForeignKey(help_text='Medio físico al que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='tecnicas', to='catalogacion.mediofisico'),
        ),
        migrations.AddField(
            model_name='tituloserie490',
            name='mencion_serie',
            field=models.ForeignKey(help_text='Mención de serie a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='titulos', to='catalogacion.mencionserie490'),
        ),
        migrations.AddField(
            model_name='volumenserie490',
            name='mencion_serie',
            field=models.ForeignKey(help_text='Mención de serie a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='volumenes', to='catalogacion.mencionserie490'),
        ),
        migrations.AlterUniqueTogether(
            name='codigopaisentidad',
            unique_together={('obra', 'codigo_pais')},
        ),
        migrations.AlterUniqueTogether(
            name='formato348',
            unique_together={('caracteristica', 'formato')},
        ),
        migrations.AlterUniqueTogether(
            name='incipitmusical',
            unique_together={('obra', 'numero_obra', 'numero_movimiento', 'numero_pasaje')},
        ),
    ]
