# Generated by Django 5.2.7 on 2025-11-17 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0006_remove_ubicacion852_institucion_persona_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obrageneral',
            name='nombre_editor',
        ),
    ]
