# Generated by Django 5.2.8 on 2026-02-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0007_rename_resto_titulo_to_subtitulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incipitmusical',
            name='tiempo',
            field=models.CharField(blank=True, help_text='031 $o – Compás', max_length=20),
        ),
        migrations.AlterField(
            model_name='incipitmusical',
            name='titulo_encabezamiento',
            field=models.CharField(blank=True, help_text='031 $d – Tempo', max_length=200),
        ),
        migrations.AlterField(
            model_name='tituloalternativo',
            name='subtitulo',
            field=models.CharField(blank=True, help_text='246 $b – Subtitulo', max_length=500, null=True),
        ),
    ]
