# Generated by Django 5.2.7 on 2025-11-17 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0007_remove_obrageneral_nombre_editor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codigolengua',
            name='fuente_especificada',
        ),
    ]
