# Generated by Django 5.2.7 on 2025-11-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0007_atribucioncompositor_caracteristicamusicanotada_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codigopaisentidad',
            options={'ordering': ['obra', 'orden', 'id'], 'verbose_name': 'País Editor/Productor (044 $a)', 'verbose_name_plural': 'Países Editor/Productor (044 $a - R)'},
        ),
        migrations.AddField(
            model_name='codigopaisentidad',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Orden de aparición en la lista de países'),
        ),
        migrations.AlterField(
            model_name='numeroobra383',
            name='numero_obra',
            field=models.CharField(help_text="383 $a – Número de obra (ej: '1', '2', 'K. 545', 'BWV 1001')", max_length=100),
        ),
    ]
