# Generated by Django 5.2.7 on 2025-11-01 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0008_alter_codigopaisentidad_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codigopaisentidad',
            options={'ordering': ['obra', 'id'], 'verbose_name': 'País Editor/Productor (044 $a)', 'verbose_name_plural': 'Países Editor/Productor (044 $a - R)'},
        ),
        migrations.RemoveField(
            model_name='codigopaisentidad',
            name='orden',
        ),
    ]
