# Generated by Django 5.2.8 on 2026-02-12 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0008_alter_incipitmusical_tiempo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncionInstitucional710',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcion', models.CharField(choices=[('coeditor', 'Coeditor'), ('dedicatario', 'Dedicatorio'), ('editor', 'Editor'), ('lugar_ejecucion', 'Lugar de ejecución'), ('lugar_estreno', 'Lugar de estreno'), ('patrocinante', 'Patrocinante')], help_text='710 $e – Función institucional', max_length=50)),
                ('entidad_710', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funciones_institucionales', to='catalogacion.entidadrelacionada710')),
            ],
            options={
                'verbose_name': '710 $e – Función institucional',
                'verbose_name_plural': '710 $e – Funciones institucionales',
            },
        ),
    ]
