# Generated by Django 5.2.7 on 2025-11-17 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0008_remove_codigolengua_fuente_especificada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codigopaisentidad',
            options={'ordering': ['obra', 'id'], 'verbose_name': 'País Editor/Productor (044 $a)', 'verbose_name_plural': 'Países Editor/Productor (044 $a)'},
        ),
        migrations.RemoveIndex(
            model_name='codigopaisentidad',
            name='catalogacio_obra_id_34e6e5_idx',
        ),
        migrations.RemoveField(
            model_name='codigopaisentidad',
            name='orden',
        ),
        migrations.AddIndex(
            model_name='codigopaisentidad',
            index=models.Index(fields=['obra'], name='catalogacio_obra_id_84d6cc_idx'),
        ),
    ]
