# Generated by Django 5.2.7 on 2025-11-03 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0009_alter_codigopaisentidad_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nombrepartesección240',
            name='obra',
        ),
        migrations.RemoveField(
            model_name='numeropartesección130',
            name='obra',
        ),
        migrations.RemoveField(
            model_name='numeropartesección240',
            name='obra',
        ),
        migrations.AlterModelOptions(
            name='atribucioncompositor',
            options={'ordering': ['obra', 'id'], 'verbose_name': 'Atribucion Compositor (100 $j)', 'verbose_name_plural': 'Atribuciones Compositor (100 $j - R)'},
        ),
        migrations.AlterModelOptions(
            name='funcioncompositor',
            options={'ordering': ['obra', 'id'], 'verbose_name': 'Funcion Compositor (100 $e)', 'verbose_name_plural': 'Funciones Compositor (100 $e - R)'},
        ),
        migrations.AlterModelOptions(
            name='mediointerpretacion130',
            options={'ordering': ['obra', 'id'], 'verbose_name': 'Medio de Interpretacion (130 $m)', 'verbose_name_plural': 'Medios de Interpretacion (130 $m - R)'},
        ),
        migrations.AlterModelOptions(
            name='mediointerpretacion240',
            options={'ordering': ['obra', 'id'], 'verbose_name': 'Medio de Interpretacion (240 $m)', 'verbose_name_plural': 'Medios de Interpretacion (240 $m - R)'},
        ),
        migrations.AlterField(
            model_name='atribucioncompositor',
            name='atribucion',
            field=models.CharField(choices=[('atribuida', 'Atribuida'), ('certificada', 'Certificada'), ('erronea', 'Erronea')], default='certificada', help_text='100 $j – Calificador de atribucion (predeterminado: certificada)', max_length=15),
        ),
        migrations.AlterField(
            model_name='atribucioncompositor',
            name='obra',
            field=models.ForeignKey(help_text='Obra a la que pertenece esta atribucion', on_delete=django.db.models.deletion.CASCADE, related_name='atribuciones_compositor', to='catalogacion.obrageneral'),
        ),
        migrations.AlterField(
            model_name='forma240',
            name='forma',
            field=models.ForeignKey(help_text='240 $k – Forma normalizada (igual que 130 $k)', on_delete=django.db.models.deletion.PROTECT, to='catalogacion.autoridadformamusical'),
        ),
        migrations.AlterField(
            model_name='funcioncompositor',
            name='funcion',
            field=models.CharField(choices=[('arreglista', 'Arreglista'), ('coeditor', 'Coeditor'), ('compilador', 'Compilador'), ('compositor', 'Compositor'), ('copista', 'Copista'), ('dedicatario', 'Dedicatario'), ('editor', 'Editor'), ('prologuista', 'Prologuista')], default='compositor', help_text='100 $e – Funcion del compositor (predeterminado: compositor)', max_length=20),
        ),
        migrations.AlterField(
            model_name='funcioncompositor',
            name='obra',
            field=models.ForeignKey(help_text='Obra a la que pertenece esta funcion', on_delete=django.db.models.deletion.CASCADE, related_name='funciones_compositor', to='catalogacion.obrageneral'),
        ),
        migrations.AlterField(
            model_name='incipitmusical',
            name='voz_instrumento',
            field=models.CharField(blank=True, default='piano', help_text='031 $m – Voz/instrumento', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mediointerpretacion130',
            name='medio',
            field=models.CharField(default='piano', help_text='130 $m – Medio de interpretacion (predeterminado: piano)', max_length=100),
        ),
        migrations.AlterField(
            model_name='mediointerpretacion240',
            name='medio',
            field=models.CharField(default='piano', help_text='240 $m – Medio de interpretacion (predeterminado: piano)', max_length=100),
        ),
        migrations.CreateModel(
            name='NombreParteSeccion130',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='130 $p – Nombre de parte/seccion (ej: Allegro, Andante, Finale)', max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(help_text='Obra a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='nombres_parte_130', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': 'Nombre de Parte/Seccion (130 $p)',
                'verbose_name_plural': 'Nombres de Parte/Seccion (130 $p - R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NombreParteSeccion240',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='240 $p – Nombre de parte/seccion (ej: Allegro, Andante, Finale)', max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(help_text='Obra a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='nombres_parte_240', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': 'Nombre de Parte/Seccion (240 $p)',
                'verbose_name_plural': 'Nombres de Parte/Seccion (240 $p - R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NumeroParteSeccion130',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='130 $n – Número de parte/seccion (ej: I, II, III o 1, 2, 3)', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(help_text='Obra a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='numeros_parte_130', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': 'Número de Parte/Seccion (130 $n)',
                'verbose_name_plural': 'Números de Parte/Seccion (130 $n - R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NumeroParteSeccion240',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='240 $n – Número de parte/seccion (ej: I, II, III o 1, 2, 3)', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(help_text='Obra a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='numeros_parte_240', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': 'Número de Parte/Seccion (240 $n)',
                'verbose_name_plural': 'Números de Parte/Seccion (240 $n - R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='NombreParteSección130',
        ),
        migrations.DeleteModel(
            name='NombreParteSección240',
        ),
        migrations.DeleteModel(
            name='NumeroParteSección130',
        ),
        migrations.DeleteModel(
            name='NumeroParteSección240',
        ),
    ]
