# Generated by Django 5.1.2 on 2025-11-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0009_alter_codigopaisentidad_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incipitmusical',
            name='voz_instrumento',
            field=models.CharField(blank=True, default='piano', help_text='031 $m – Voz/instrumento', max_length=100, null=True),
        ),
    ]
