# Generated by Django 5.2.7 on 2025-11-17 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0009_alter_codigopaisentidad_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autoridadpersona',
            old_name='fechas',
            new_name='coordenadas_biograficas',
        ),
        migrations.AddField(
            model_name='obrageneral',
            name='termino_asociado',
            field=models.CharField(blank=True, help_text='100 $c — Término asociado al nombre', max_length=200, null=True),
        ),
    ]
