# Generated by Django 5.2.8 on 2026-02-13 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0009_add_funcion_institucional_710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entidadrelacionada710',
            name='funcion',
        ),
        migrations.AlterField(
            model_name='funcion700',
            name='funcion',
            field=models.CharField(choices=[('arreglista', 'Arreglista'), ('coeditor', 'Coeditor'), ('compilador', 'Compilador'), ('compositor', 'Compositor'), ('copista', 'Copista'), ('dedicatario', 'Dedicatario'), ('editor', 'Editor'), ('prologuista', 'Prologuista')], help_text='700 $e – Función (R)', max_length=30),
        ),
        migrations.AlterField(
            model_name='funcioninstitucional710',
            name='funcion',
            field=models.CharField(choices=[('coeditor', 'Coeditor'), ('dedicatario', 'Dedicatario'), ('editor', 'Editor'), ('lugar_ejecucion', 'Lugar de ejecución'), ('lugar_estreno', 'Lugar de estreno'), ('patrocinante', 'Patrocinante')], help_text='710 $e – Función institucional', max_length=50),
        ),
    ]
