# Generated by Django 5.2.7 on 2025-11-17 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0010_rename_fechas_autoridadpersona_coordenadas_biograficas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enlacedocumentofuente773',
            name='numero_obra_relacionada',
        ),
        migrations.RemoveField(
            model_name='enlaceunidadconstituyente774',
            name='numero_obra_relacionada',
        ),
        migrations.CreateModel(
            name='NumeroObraRelacionada773',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='773 $w – Número de control 001 del registro de documento fuente', max_length=50)),
                ('enlace_773', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numeros_obra', to='catalogacion.enlacedocumentofuente773')),
            ],
            options={
                'verbose_name': '773 $w – Número de obra',
                'verbose_name_plural': '773 $w – Números de obra (R)',
                'ordering': ['enlace_773', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NumeroObraRelacionada774',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='774 $w – Número de control de la obra constituyente', max_length=50)),
                ('enlace_774', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numeros_obra', to='catalogacion.enlaceunidadconstituyente774')),
            ],
            options={
                'verbose_name': '774 $w – Número de obra',
                'verbose_name_plural': '774 $w – Números de obra (R)',
                'ordering': ['enlace_774', 'id'],
            },
        ),
    ]
