# Generated by Django 5.2.8 on 2026-02-18 00:09

from django.db import migrations


FORMAS_ESTANDAR_130_240 = [
    "adaptación",
    "boceto",
    "fragmento",
    "selección",
    "tema con variaciones",
]


def seed_formas_musicales(apps, schema_editor):
    """Crear los 5 valores estándar MARC21 para 130 $k / 240 $k si no existen."""
    AutoridadFormaMusical = apps.get_model('catalogacion', 'AutoridadFormaMusical')
    for forma in FORMAS_ESTANDAR_130_240:
        AutoridadFormaMusical.objects.get_or_create(forma=forma)


def reverse_seed_formas_musicales(apps, schema_editor):
    """Eliminar solo las formas creadas por esta migración si no están en uso."""
    AutoridadFormaMusical = apps.get_model('catalogacion', 'AutoridadFormaMusical')
    for forma in FORMAS_ESTANDAR_130_240:
        AutoridadFormaMusical.objects.filter(
            forma=forma,
            obras_forma_130__isnull=True,
            obras_forma_240__isnull=True,
        ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0010_remove_funcion_from_entidadrelacionada710'),
    ]

    operations = [
        migrations.RunPython(
            seed_formas_musicales,
            reverse_code=reverse_seed_formas_musicales,
        ),
    ]
