# Generated by Django 5.1.2 on 2025-11-04 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0010_alter_incipitmusical_voz_instrumento'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoridadEntidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300, unique=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Autoridad de entidad',
                'verbose_name_plural': 'Autoridades de entidades',
            },
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_indicador', models.CharField(default='0', help_text='Primer indicador: Tipo de contenido', max_length=1)),
                ('segundo_indicador', models.CharField(default='0', help_text='Segundo indicador: Forma de visualización', max_length=1)),
                ('contenido', models.TextField(help_text='505 $a – Contenido de la obra (R)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(help_text='Obra a la que pertenece este contenido', on_delete=django.db.models.deletion.CASCADE, related_name='contenidos', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': 'Contenido (505)',
                'verbose_name_plural': 'Contenidos (505 - R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DatosBiograficosCompositor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_indicador', models.CharField(default='0', help_text='Primer indicador: Tipo de biografía', max_length=1)),
                ('segundo_indicador', models.CharField(default='#', help_text='Segundo indicador: No definido', max_length=1)),
                ('datos_biograficos', models.TextField(help_text='545 $a – Datos biográficos del compositor (R)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(help_text='Obra a la que pertenecen estos datos biográficos', on_delete=django.db.models.deletion.CASCADE, related_name='datos_biograficos_compositor', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': 'Datos Biográficos del Compositor (545)',
                'verbose_name_plural': 'Datos Biográficos del Compositor (545 - R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Enlace856',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_indicador', models.CharField(default='4', help_text='Primer indicador: Método de acceso (4 = HTTP, URL)', max_length=1)),
                ('segundo_indicador', models.CharField(default='#', help_text='Segundo indicador: Relación (no definido)', max_length=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(help_text='Obra a la que pertenece este enlace', on_delete=django.db.models.deletion.CASCADE, related_name='enlaces_856', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': '856 – Enlace disponible',
                'verbose_name_plural': '856 – Enlaces disponibles (R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EnlaceDocumentoFuente773',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encabezamiento_principal', models.CharField(help_text='773 $a – Encabezamiento principal (NR, controlado por autoridades)', max_length=500)),
                ('titulo', models.CharField(help_text='773 $t – Título (NR)', max_length=500)),
                ('primer_indicador', models.CharField(default='1', max_length=1)),
                ('segundo_indicador', models.CharField(default='#', max_length=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enlaces_doc_fuente_773', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': '773 – Enlace a documento fuente',
                'verbose_name_plural': '773 – Enlaces a documento fuente (R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EnlaceUnidadConstituyente774',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encabezamiento_principal', models.CharField(help_text='774 $a – Encabezamiento principal (NR, autoridad)', max_length=500)),
                ('titulo', models.CharField(help_text='774 $t – Título (NR)', max_length=500)),
                ('primer_indicador', models.CharField(default='1', max_length=1)),
                ('segundo_indicador', models.CharField(default='#', max_length=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enlaces_unidad_774', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': '774 – Enlace a unidad constituyente',
                'verbose_name_plural': '774 – Enlaces a unidades constituyentes (R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EntidadRelacionada710',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_indicador', models.CharField(default='2', max_length=1)),
                ('segundo_indicador', models.CharField(default='#', max_length=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('entidad', models.ForeignKey(help_text='710 $a – Entidad/Jurisdicción (controlado, NR)', on_delete=django.db.models.deletion.PROTECT, to='catalogacion.autoridadentidad')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entidades_relacionadas_710', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': '710 – Entidad relacionada',
                'verbose_name_plural': '710 – Entidades relacionadas (R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Funcion710',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcion', models.CharField(choices=[('coeditor', 'Coeditor'), ('dedicatario', 'Dedicatario'), ('editor', 'Editor'), ('lugar_ejecucion', 'Lugar de ejecución'), ('lugar_estreno', 'Lugar de estreno'), ('patrocinante', 'Patrocinante')], help_text='710 $e – Función institucional (R)', max_length=30)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('entidad_710', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funciones', to='catalogacion.entidadrelacionada710')),
            ],
            options={
                'verbose_name': '710 $e – Función',
                'verbose_name_plural': '710 $e – Funciones (R)',
                'ordering': ['entidad_710', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MateriaGeneroForma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_indicador', models.CharField(default='#', help_text='Primer indicador (no definido)', max_length=1)),
                ('segundo_indicador', models.CharField(default='4', help_text='Segundo indicador (fuente del encabezamiento)', max_length=1)),
                ('materia_genero', models.CharField(help_text='655 $a – Materia (Género/forma) (NR)', max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(help_text='Obra a la que pertenece esta materia de género/forma', on_delete=django.db.models.deletion.CASCADE, related_name='materias_genero_forma', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': 'Materia (Género/forma) (655)',
                'verbose_name_plural': 'Materias (Género/forma) (655 - R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MateriaTemas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_indicador', models.CharField(default='0', help_text='Primer indicador (nivel de encabezamiento)', max_length=1)),
                ('segundo_indicador', models.CharField(default='4', help_text='Segundo indicador (fuente del encabezamiento)', max_length=1)),
                ('materia', models.CharField(help_text='650 $a – Materia o tema principal (NR)', max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(help_text='Obra a la que pertenece esta materia temática', on_delete=django.db.models.deletion.CASCADE, related_name='materias_temas', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': 'Materia (650)',
                'verbose_name_plural': 'Materias Temáticas (650 - R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NombreRelacionado700',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechas', models.CharField(blank=True, help_text='700 $d – Fechas asociadas al nombre (NR, p. ej., 1850-1910)', max_length=50, null=True)),
                ('titulo_obra', models.CharField(blank=True, help_text='700 $t – Título de la obra (NR)', max_length=500, null=True)),
                ('primer_indicador', models.CharField(default='1', help_text='Primer indicador (siempre 1 para nombre de persona)', max_length=1)),
                ('segundo_indicador', models.CharField(default='#', help_text='Segundo indicador (no definido)', max_length=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(help_text='Obra a la que se vincula este 700', on_delete=django.db.models.deletion.CASCADE, related_name='nombres_relacionados_700', to='catalogacion.obrageneral')),
                ('persona', models.ForeignKey(help_text='700 $a – Apellidos, Nombres (controlado, NR)', on_delete=django.db.models.deletion.PROTECT, to='catalogacion.autoridadpersona')),
            ],
            options={
                'verbose_name': '700 – Nombre relacionado',
                'verbose_name_plural': '700 – Nombres relacionados (R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Funcion700',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcion', models.CharField(choices=[('arreglista', 'Arreglista'), ('coeditor', 'Coeditor'), ('compilador', 'Compilador'), ('compositor', 'Compositor'), ('copista', 'Copista'), ('dedicatario', 'Dedicatario'), ('editor', 'Editor'), ('prologuista', 'Prologuista')], help_text='700 $e – Función (R)', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('nombre_700', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funciones', to='catalogacion.nombrerelacionado700')),
            ],
            options={
                'verbose_name': '700 $e – Función',
                'verbose_name_plural': '700 $e – Funciones (R)',
                'ordering': ['nombre_700', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Atribucion700',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atribucion', models.CharField(choices=[('atribuida', 'Atribuida'), ('certificada', 'Certificada'), ('erronea', 'Errónea')], default='certificada', help_text='700 $j – Calificador de atribución (R)', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('nombre_700', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atribuciones', to='catalogacion.nombrerelacionado700')),
            ],
            options={
                'verbose_name': '700 $j – Atribución',
                'verbose_name_plural': '700 $j – Atribuciones (R)',
                'ordering': ['nombre_700', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NotaGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.TextField(help_text='500 $a – Nota general (R)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(help_text='Obra a la que pertenece esta nota general', on_delete=django.db.models.deletion.CASCADE, related_name='notas_generales', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': 'Nota general (500)',
                'verbose_name_plural': 'Notas generales (500 - R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NumeroControl773',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_control', models.CharField(help_text='773 $w – Número de control 001 del documento fuente (R)', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('enlace_773', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numeros_control', to='catalogacion.enlacedocumentofuente773')),
                ('obra_relacionada', models.ForeignKey(blank=True, help_text='Referencia interna por si el 001 pertenece a esta base', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referencias_entrantes_773', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': '773 $w – N° control',
                'verbose_name_plural': '773 $w – N° control (R)',
                'ordering': ['enlace_773', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NumeroControl774',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_control', models.CharField(help_text='774 $w – Número de control 001 del asiento analítico (R)', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('enlace_774', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numeros_control', to='catalogacion.enlaceunidadconstituyente774')),
                ('obra_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referencias_entrantes_774', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': '774 $w – N° control',
                'verbose_name_plural': '774 $w – N° control (R)',
                'ordering': ['enlace_774', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OtrasRelaciones787',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encabezamiento_principal', models.CharField(help_text='787 $a – Encabezamiento principal (NR, autoridad)', max_length=500)),
                ('titulo', models.CharField(help_text='787 $t – Título (NR)', max_length=500)),
                ('primer_indicador', models.CharField(default='1', max_length=1)),
                ('segundo_indicador', models.CharField(default='#', max_length=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otras_relaciones_787', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': '787 – Otras relaciones',
                'verbose_name_plural': '787 – Otras relaciones (R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NumeroControl787',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_control', models.CharField(help_text='787 $w – Número de control 001 del registro relacionado (R)', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('obra_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referencias_entrantes_787', to='catalogacion.obrageneral')),
                ('relacion_787', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numeros_control', to='catalogacion.otrasrelaciones787')),
            ],
            options={
                'verbose_name': '787 $w – N° control',
                'verbose_name_plural': '787 $w – N° control (R)',
                'ordering': ['relacion_787', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Relacion700',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='700 $i – Información sobre la relación (R)', max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('nombre_700', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones', to='catalogacion.nombrerelacionado700')),
            ],
            options={
                'verbose_name': '700 $i – Relación',
                'verbose_name_plural': '700 $i – Relaciones (R)',
                'ordering': ['nombre_700', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SubdivisionGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdivision', models.CharField(help_text='655 $x – Subdivisión general (R)', max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('materia_genero', models.ForeignKey(help_text='Materia de género/forma a la que pertenece esta subdivisión general', on_delete=django.db.models.deletion.CASCADE, related_name='subdivisiones_generales', to='catalogacion.materiageneroforma')),
            ],
            options={
                'verbose_name': 'Subdivisión General (655 $x)',
                'verbose_name_plural': 'Subdivisiones Generales (655 $x - R)',
                'ordering': ['materia_genero', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SubdivisionMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdivision', models.CharField(help_text='650 $x – Subdivisión de materia (R)', max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('materia_tema', models.ForeignKey(help_text='Materia temática a la que pertenece esta subdivisión', on_delete=django.db.models.deletion.CASCADE, related_name='subdivisiones', to='catalogacion.materiatemas')),
            ],
            options={
                'verbose_name': 'Subdivisión de Materia (650 $x)',
                'verbose_name_plural': 'Subdivisiones de Materia (650 $x - R)',
                'ordering': ['materia_tema', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Sumario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sumario', models.TextField(help_text='520 $a – Sumario o sinopsis (NR)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(help_text='Obra a la que pertenece este sumario', on_delete=django.db.models.deletion.CASCADE, related_name='sumarios', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': 'Sumario (520)',
                'verbose_name_plural': 'Sumarios (520 - R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TextoEnlace856',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(help_text='856 $y – Texto o descripción del enlace (R)', max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('enlace', models.ForeignKey(help_text='Enlace 856 al que pertenece este texto', on_delete=django.db.models.deletion.CASCADE, related_name='textos_enlace', to='catalogacion.enlace856')),
            ],
            options={
                'verbose_name': '856 $y – Texto del enlace',
                'verbose_name_plural': '856 $y – Textos del enlace (R)',
                'ordering': ['enlace', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Ubicacion852',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_indicador', models.CharField(default='#', help_text='Primer indicador: No definido (#)', max_length=1)),
                ('segundo_indicador', models.CharField(default='#', help_text='Segundo indicador: No definido (#)', max_length=1)),
                ('institucion', models.CharField(help_text='852 $a – Institución o persona responsable (NR)', max_length=255)),
                ('signatura_original', models.CharField(blank=True, help_text='852 $h – Signatura original (NR)', max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(help_text='Obra a la que pertenece esta ubicación', on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones_852', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': '852 – Ubicación',
                'verbose_name_plural': '852 – Ubicaciones (R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Estanteria852',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estanteria', models.CharField(help_text='852 $c – Estantería o sección (R)', max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ubicacion', models.ForeignKey(help_text='Ubicación principal a la que pertenece esta estantería', on_delete=django.db.models.deletion.CASCADE, related_name='estanterias', to='catalogacion.ubicacion852')),
            ],
            options={
                'verbose_name': '852 $c – Estantería',
                'verbose_name_plural': '852 $c – Estanterías (R)',
                'ordering': ['ubicacion', 'id'],
            },
        ),
        migrations.CreateModel(
            name='URLBiografica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='545 $u – URL (R)', max_length=500)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('datos_biograficos', models.ForeignKey(help_text='Registro biográfico al que pertenece esta URL', on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='catalogacion.datosbiograficoscompositor')),
            ],
            options={
                'verbose_name': 'URL Biográfica (545 $u)',
                'verbose_name_plural': 'URLs Biográficas (545 $u - R)',
                'ordering': ['datos_biograficos', 'id'],
            },
        ),
        migrations.CreateModel(
            name='URLEnlace856',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='856 $u – URL del recurso electrónico (R)', max_length=500)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('enlace', models.ForeignKey(help_text='Enlace 856 al que pertenece esta URL', on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='catalogacion.enlace856')),
            ],
            options={
                'verbose_name': '856 $u – URL',
                'verbose_name_plural': '856 $u – URLs (R)',
                'ordering': ['enlace', 'id'],
            },
        ),
    ]
