# Generated by Django 5.2.7 on 2025-11-05 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0010_remove_nombrepartesección240_obra_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idiomaobra',
            old_name='codigo',
            new_name='codigo_idioma',
        ),
        migrations.RenameField(
            model_name='numeroeditor',
            old_name='numero',
            new_name='numero_editor',
        ),
    ]
