# Generated by Django 5.1.2 on 2025-11-04 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0011_autoridadentidad_contenido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcion710',
            name='obra',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='funciones_710', to='catalogacion.obrageneral'),
            preserve_default=False,
        ),
    ]
