# Generated by Django 5.2.8 on 2026-02-18 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0011_seed_formas_musicales_130_240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediointerpretacion382',
            name='solista',
            field=models.CharField(blank=True, default='piano', help_text='382 $b — Solista (predeterminado: piano)', max_length=100, null=True),
        ),
    ]
