# Generated by Django 5.2.7 on 2025-11-17 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0011_remove_enlacedocumentofuente773_numero_obra_relacionada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enlacedocumentofuente773',
            name='encabezamiento_principal',
        ),
        migrations.RemoveField(
            model_name='enlaceunidadconstituyente774',
            name='encabezamiento_principal',
        ),
        migrations.AddField(
            model_name='enlacedocumentofuente773',
            name='compositor_773',
            field=models.ForeignKey(default=1, help_text='773 $a – Compositor (Persona, Título o Entidad)', on_delete=django.db.models.deletion.PROTECT, to='catalogacion.encabezamientoenlace'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enlaceunidadconstituyente774',
            name='compositor_774',
            field=models.ForeignKey(default=1, help_text='774 $a – Compositor (Persona, Título o Entidad)', on_delete=django.db.models.deletion.PROTECT, to='catalogacion.encabezamientoenlace'),
            preserve_default=False,
        ),
    ]
