# Generated by Django 5.2.7 on 2025-11-17 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0012_remove_enlacedocumentofuente773_encabezamiento_principal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otrasrelaciones787',
            old_name='encabezamiento_principal',
            new_name='compositor_787',
        ),
        migrations.RemoveField(
            model_name='otrasrelaciones787',
            name='numero_obra_relacionada',
        ),
        migrations.CreateModel(
            name='NumeroObraRelacionada787',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='787 $w – Número de control de la obra relacionada', max_length=50)),
                ('enlace_787', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numeros_obra', to='catalogacion.otrasrelaciones787')),
            ],
            options={
                'verbose_name': '787 $w – Número de obra',
                'verbose_name_plural': '787 $w – Números de obra (R)',
                'ordering': ['enlace_787', 'id'],
            },
        ),
    ]
