# Generated by Django 5.1.2 on 2025-11-05 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0012_funcion710_obra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcion710',
            name='entidad_710',
        ),
        migrations.RemoveField(
            model_name='funcion710',
            name='obra',
        ),
        migrations.RemoveField(
            model_name='numerocontrol773',
            name='enlace_773',
        ),
        migrations.RemoveField(
            model_name='numerocontrol773',
            name='obra_relacionada',
        ),
        migrations.RemoveField(
            model_name='numerocontrol774',
            name='enlace_774',
        ),
        migrations.RemoveField(
            model_name='numerocontrol774',
            name='obra_relacionada',
        ),
        migrations.RemoveField(
            model_name='numerocontrol787',
            name='obra_relacionada',
        ),
        migrations.RemoveField(
            model_name='numerocontrol787',
            name='relacion_787',
        ),
        migrations.AlterModelOptions(
            name='enlacedocumentofuente773',
            options={'ordering': ['obra', 'id'], 'verbose_name': '773 – Documento fuente', 'verbose_name_plural': '773 – Documentos fuente (R)'},
        ),
        migrations.AlterModelOptions(
            name='enlaceunidadconstituyente774',
            options={'ordering': ['obra', 'id'], 'verbose_name': '774 – Unidad constituyente', 'verbose_name_plural': '774 – Unidades constituyentes (R)'},
        ),
        migrations.AlterModelOptions(
            name='otrasrelaciones787',
            options={'ordering': ['obra', 'id'], 'verbose_name': '787 – Otra relación', 'verbose_name_plural': '787 – Otras relaciones (R)'},
        ),
        migrations.RemoveField(
            model_name='enlacedocumentofuente773',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='enlacedocumentofuente773',
            name='primer_indicador',
        ),
        migrations.RemoveField(
            model_name='enlacedocumentofuente773',
            name='segundo_indicador',
        ),
        migrations.RemoveField(
            model_name='enlaceunidadconstituyente774',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='enlaceunidadconstituyente774',
            name='primer_indicador',
        ),
        migrations.RemoveField(
            model_name='enlaceunidadconstituyente774',
            name='segundo_indicador',
        ),
        migrations.RemoveField(
            model_name='entidadrelacionada710',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='entidadrelacionada710',
            name='primer_indicador',
        ),
        migrations.RemoveField(
            model_name='entidadrelacionada710',
            name='segundo_indicador',
        ),
        migrations.RemoveField(
            model_name='funcion700',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='nombrerelacionado700',
            name='primer_indicador',
        ),
        migrations.RemoveField(
            model_name='nombrerelacionado700',
            name='segundo_indicador',
        ),
        migrations.RemoveField(
            model_name='otrasrelaciones787',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='otrasrelaciones787',
            name='primer_indicador',
        ),
        migrations.RemoveField(
            model_name='otrasrelaciones787',
            name='segundo_indicador',
        ),
        migrations.RemoveField(
            model_name='relacion700',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='enlacedocumentofuente773',
            name='numero_obra_relacionada',
            field=models.CharField(blank=True, help_text='773 $w – Número de obra relacionada (R)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='enlaceunidadconstituyente774',
            name='numero_obra_relacionada',
            field=models.CharField(blank=True, help_text='774 $w – Número de obra relacionada (R)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='entidadrelacionada710',
            name='funcion',
            field=models.CharField(blank=True, choices=[('coeditor', 'Coeditor'), ('dedicatario', 'Dedicatorio'), ('editor', 'Editor'), ('lugar_ejecucion', 'Lugar de ejecución'), ('lugar_estreno', 'Lugar de estreno'), ('patrocinante', 'Patrocinante')], help_text='710 $e – Función institucional (R)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='otrasrelaciones787',
            name='numero_obra_relacionada',
            field=models.CharField(blank=True, help_text='787 $w – Número de obra relacionada (R)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enlacedocumentofuente773',
            name='encabezamiento_principal',
            field=models.ForeignKey(help_text='773 $a – Encabezamiento principal (NR)', on_delete=django.db.models.deletion.PROTECT, to='catalogacion.autoridadpersona'),
        ),
        migrations.AlterField(
            model_name='enlacedocumentofuente773',
            name='obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enlaces_documento_fuente_773', to='catalogacion.obrageneral'),
        ),
        migrations.AlterField(
            model_name='enlacedocumentofuente773',
            name='titulo',
            field=models.CharField(help_text='773 $t – Título (NR)', max_length=250),
        ),
        migrations.AlterField(
            model_name='enlaceunidadconstituyente774',
            name='encabezamiento_principal',
            field=models.ForeignKey(help_text='774 $a – Encabezamiento principal (NR)', on_delete=django.db.models.deletion.PROTECT, to='catalogacion.autoridadpersona'),
        ),
        migrations.AlterField(
            model_name='enlaceunidadconstituyente774',
            name='obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enlaces_unidades_774', to='catalogacion.obrageneral'),
        ),
        migrations.AlterField(
            model_name='enlaceunidadconstituyente774',
            name='titulo',
            field=models.CharField(help_text='774 $t – Título (NR)', max_length=250),
        ),
        migrations.AlterField(
            model_name='funcion700',
            name='funcion',
            field=models.CharField(choices=[('arreglista', 'Arreglista'), ('coeditor', 'Coeditor'), ('compilador', 'Compilador'), ('compositor', 'Compositor'), ('copista', 'Copista'), ('dedicatario', 'Dedicatorio'), ('editor', 'Editor'), ('prologuista', 'Prologuista')], help_text='700 $e – Función (R)', max_length=30),
        ),
        migrations.AlterField(
            model_name='nombrerelacionado700',
            name='fechas',
            field=models.CharField(blank=True, help_text='700 $d – Fechas asociadas al nombre (NR)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nombrerelacionado700',
            name='obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nombres_relacionados_700', to='catalogacion.obrageneral'),
        ),
        migrations.AlterField(
            model_name='nombrerelacionado700',
            name='titulo_obra',
            field=models.CharField(blank=True, help_text='700 $t – Título de la obra (NR)', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='otrasrelaciones787',
            name='encabezamiento_principal',
            field=models.ForeignKey(help_text='787 $a – Encabezamiento principal (NR)', on_delete=django.db.models.deletion.PROTECT, to='catalogacion.autoridadpersona'),
        ),
        migrations.AlterField(
            model_name='otrasrelaciones787',
            name='titulo',
            field=models.CharField(help_text='787 $t – Título (NR)', max_length=250),
        ),
        migrations.AlterField(
            model_name='relacion700',
            name='descripcion',
            field=models.CharField(help_text='700 $i – Relación (R)', max_length=200),
        ),
        migrations.CreateModel(
            name='Autoria700',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autoria', models.CharField(choices=[('atribuida', 'Atribuida'), ('certificada', 'Certificada'), ('erronea', 'Errónea')], default='certificada', help_text='700 $j – Autoría (R)', max_length=20)),
                ('nombre_700', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autoridades_autoria', to='catalogacion.nombrerelacionado700')),
            ],
            options={
                'verbose_name': '700 $j – Autoría',
                'verbose_name_plural': '700 $j – Autorías (R)',
                'ordering': ['nombre_700', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TerminoAsociado700',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termino', models.CharField(help_text='700 $c – Término asociado al nombre (R)', max_length=100)),
                ('nombre_700', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminos_asociados', to='catalogacion.nombrerelacionado700')),
            ],
            options={
                'verbose_name': '700 $c – Término asociado',
                'verbose_name_plural': '700 $c – Términos asociados (R)',
                'ordering': ['nombre_700', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='Atribucion700',
        ),
        migrations.DeleteModel(
            name='Funcion710',
        ),
        migrations.DeleteModel(
            name='NumeroControl773',
        ),
        migrations.DeleteModel(
            name='NumeroControl774',
        ),
        migrations.DeleteModel(
            name='NumeroControl787',
        ),
    ]
