# Generated by Django 5.2.7 on 2025-11-17 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0013_rename_encabezamiento_principal_otrasrelaciones787_compositor_787_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obrageneral',
            name='institucion_persona_852a',
        ),
        migrations.RemoveField(
            model_name='obrageneral',
            name='signatura_original_852h',
        ),
        migrations.AddField(
            model_name='ubicacion852',
            name='institucion_persona',
            field=models.ForeignKey(blank=True, help_text='852 $a — Institución o persona', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ubicaciones_852', to='catalogacion.autoridadentidad'),
        ),
        migrations.AddField(
            model_name='ubicacion852',
            name='signatura_original',
            field=models.CharField(blank=True, help_text='852 $h — Signatura original', max_length=255, null=True),
        ),
    ]
