# Generated by Django 5.1.2 on 2025-11-05 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0013_remove_funcion710_entidad_710_remove_funcion710_obra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enlaceunidadconstituyente774',
            name='encabezamiento_principal',
            field=models.ForeignKey(help_text='774 $a – Encabezamiento principal (NR)', on_delete=django.db.models.deletion.PROTECT, to='catalogacion.autoridadentidad'),
        ),
    ]
