# Generated by Django 5.1.2 on 2025-11-05 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0014_alter_enlaceunidadconstituyente774_encabezamiento_principal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosbiograficoscompositor',
            name='obra',
        ),
        migrations.RemoveField(
            model_name='urlbiografica',
            name='datos_biograficos',
        ),
        migrations.RemoveField(
            model_name='notageneral',
            name='obra',
        ),
        migrations.RemoveField(
            model_name='sumario',
            name='obra',
        ),
        migrations.CreateModel(
            name='Contenido505',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(blank=True, help_text='505 $a – Contenido (R)', null=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenidos_505', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': '505 – Contenido',
                'verbose_name_plural': '505 – Contenidos (R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DatosBiograficos545',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos_biograficos', models.TextField(blank=True, help_text='545 $a – Datos biográficos del compositor (R)', null=True)),
                ('url', models.URLField(blank=True, help_text='545 $u – URL (R)', null=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datos_biograficos_545', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': '545 – Datos biográficos del compositor',
                'verbose_name_plural': '545 – Datos biográficos del compositor (R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NotaGeneral500',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_general', models.TextField(blank=True, help_text='500 $a – Nota general (R)', null=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_generales_500', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': '500 – Nota general',
                'verbose_name_plural': '500 – Notas generales (R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Sumario520',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sumario', models.TextField(blank=True, help_text='520 $a – Sumario (NR)', null=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sumarios_520', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': '520 – Sumario',
                'verbose_name_plural': '520 – Sumarios (R)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='Contenido',
        ),
        migrations.DeleteModel(
            name='DatosBiograficosCompositor',
        ),
        migrations.DeleteModel(
            name='URLBiografica',
        ),
        migrations.DeleteModel(
            name='NotaGeneral',
        ),
        migrations.DeleteModel(
            name='Sumario',
        ),
    ]
