# Generated by Django 5.2.7 on 2025-11-18 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0014_remove_obrageneral_institucion_persona_852a_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mencionserie490',
            name='relacion',
        ),
    ]
