# Generated by Django 5.1.2 on 2025-11-05 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0015_remove_datosbiograficoscompositor_obra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subdivisiongeneral',
            name='materia_genero',
        ),
        migrations.RemoveField(
            model_name='materiatemas',
            name='obra',
        ),
        migrations.RemoveField(
            model_name='subdivisionmateria',
            name='materia_tema',
        ),
        migrations.CreateModel(
            name='Materia650',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(help_text='650 $a – Materia principal', max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_650', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': '650 – Materia (Tema)',
                'verbose_name_plural': '650 – Materias (Temas)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MateriaGenero655',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(help_text='655 $a – Materia (género/forma)', max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_655', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': '655 – Materia (Género/forma)',
                'verbose_name_plural': '655 – Materias (Género/forma)',
                'ordering': ['obra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SubdivisionGeneral655',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdivision', models.CharField(help_text='655 $x – Subdivisión general', max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('materia655', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdivisiones', to='catalogacion.materiagenero655')),
            ],
            options={
                'verbose_name': '655 $x – Subdivisión general',
                'verbose_name_plural': '655 $x – Subdivisiones generales (R)',
                'ordering': ['materia655', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SubdivisionMateria650',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdivision', models.CharField(help_text='650 $x – Subdivisión de materia', max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('materia650', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdivisiones', to='catalogacion.materia650')),
            ],
            options={
                'verbose_name': '650 $x – Subdivisión de materia',
                'verbose_name_plural': '650 $x – Subdivisiones de materia (R)',
                'ordering': ['materia650', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='MateriaGeneroForma',
        ),
        migrations.DeleteModel(
            name='SubdivisionGeneral',
        ),
        migrations.DeleteModel(
            name='MateriaTemas',
        ),
        migrations.DeleteModel(
            name='SubdivisionMateria',
        ),
    ]
