# Generated by Django 5.2.7 on 2025-11-18 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0015_remove_mencionserie490_relacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosbiograficos545',
            name='datos_biograficos',
        ),
        migrations.RemoveField(
            model_name='datosbiograficos545',
            name='url',
        ),
        migrations.CreateModel(
            name='TextoBiografico545',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, help_text='545 $a – Datos biográficos del compositor (R)', null=True)),
                ('dato_biografico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textos_biograficos_545', to='catalogacion.datosbiograficos545')),
            ],
            options={
                'verbose_name': '545 $a – Texto biográfico',
                'verbose_name_plural': '545 $a – Textos biográficos (R)',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='URI545',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.URLField(blank=True, help_text='545 $u – URI (R)', null=True)),
                ('dato_biografico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uris_545', to='catalogacion.datosbiograficos545')),
            ],
            options={
                'verbose_name': '545 $u – URI',
                'verbose_name_plural': '545 $u – URIs (R)',
                'ordering': ['id'],
            },
        ),
    ]
