# Generated by Django 5.1.2 on 2025-11-05 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0016_remove_subdivisiongeneral_materia_genero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enlace856',
            name='obra',
        ),
        migrations.RemoveField(
            model_name='textoenlace856',
            name='enlace',
        ),
        migrations.RemoveField(
            model_name='estanteria852',
            name='ubicacion',
        ),
        migrations.AlterModelOptions(
            name='ubicacion852',
            options={'ordering': ['institucion'], 'verbose_name': 'Ubicación (852)', 'verbose_name_plural': '📚 Ubicaciones (852)'},
        ),
        migrations.RemoveField(
            model_name='ubicacion852',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='ubicacion852',
            name='primer_indicador',
        ),
        migrations.RemoveField(
            model_name='ubicacion852',
            name='segundo_indicador',
        ),
        migrations.RemoveField(
            model_name='ubicacion852',
            name='signatura_original',
        ),
        migrations.AddField(
            model_name='ubicacion852',
            name='estanteria',
            field=models.CharField(blank=True, help_text='Ubicación física dentro de la institución. Ej: Sala Música Antigua, Estante 4B.', max_length=150, verbose_name='Estantería / Departamento ($c)'),
        ),
        migrations.AddField(
            model_name='ubicacion852',
            name='signatura',
            field=models.CharField(blank=True, help_text='Número o código de signatura topográfica del ejemplar. Ej: UNL-MUS-0456', max_length=100, verbose_name='Signatura original ($h)'),
        ),
        migrations.AlterField(
            model_name='ubicacion852',
            name='institucion',
            field=models.CharField(help_text='Nombre de la institución o persona responsable del ejemplar. Ej: Universidad Nacional de Loja', max_length=200, verbose_name='Institución o persona ($a)'),
        ),
        migrations.AlterField(
            model_name='ubicacion852',
            name='obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones_852', to='catalogacion.obrageneral'),
        ),
        migrations.CreateModel(
            name='Disponible856',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='Enlace al recurso digital o documento en línea.', max_length=500, verbose_name='URL ($u)')),
                ('texto_enlace', models.CharField(blank=True, help_text='Texto descriptivo del enlace. Ej: Ver partitura digital, Escuchar grabación.', max_length=200, verbose_name='Texto del enlace ($y)')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibles_856', to='catalogacion.obrageneral')),
            ],
            options={
                'verbose_name': 'Disponible (856)',
                'verbose_name_plural': '🌐 Disponibles (856)',
                'ordering': ['url'],
            },
        ),
        migrations.DeleteModel(
            name='URLEnlace856',
        ),
        migrations.DeleteModel(
            name='Enlace856',
        ),
        migrations.DeleteModel(
            name='TextoEnlace856',
        ),
        migrations.DeleteModel(
            name='Estanteria852',
        ),
    ]
