# Generated by Django 5.2.7 on 2025-11-18 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0016_remove_datosbiograficos545_datos_biograficos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorradorObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_obra', models.CharField(help_text='Tipo de obra MARC21: manuscrito, impreso, coleccion, etc.', max_length=50)),
                ('datos_formulario', models.JSONField(help_text='Datos del formulario serializados en JSON')),
                ('pestana_actual', models.IntegerField(default=0, help_text='Índice de la pestaña actual (0-8)')),
                ('titulo_temporal', models.CharField(blank=True, help_text='Título extraído del campo 245$a para mostrar en la lista', max_length=500)),
                ('num_control_temporal', models.CharField(blank=True, help_text='Número de control temporal si existe', max_length=50)),
                ('tipo_registro', models.CharField(blank=True, help_text='c=impreso, d=manuscrito', max_length=1)),
                ('nivel_bibliografico', models.CharField(blank=True, help_text='a=parte, c=colección, m=monografía', max_length=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Borrador de Obra MARC21',
                'verbose_name_plural': 'Borradores de Obras MARC21',
                'db_table': 'catalogacion_borrador_obra',
                'ordering': ['-fecha_modificacion'],
                'indexes': [models.Index(fields=['-fecha_modificacion'], name='catalogacio_fecha_m_0af39e_idx'), models.Index(fields=['tipo_obra'], name='catalogacio_tipo_ob_554f30_idx'), models.Index(fields=['tipo_registro'], name='catalogacio_tipo_re_9d7553_idx')],
            },
        ),
    ]
