# Generated by Django 5.1.2 on 2025-11-05 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0017_remove_enlace856_obra_remove_textoenlace856_enlace_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disponible856',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ubicacion852',
            options={},
        ),
        migrations.RemoveField(
            model_name='ubicacion852',
            name='estanteria',
        ),
        migrations.AlterField(
            model_name='disponible856',
            name='texto_enlace',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Texto del enlace ($y)'),
        ),
        migrations.AlterField(
            model_name='disponible856',
            name='url',
            field=models.URLField(verbose_name='URL ($u)'),
        ),
        migrations.AlterField(
            model_name='ubicacion852',
            name='institucion',
            field=models.CharField(max_length=255, verbose_name='Institución o persona ($a)'),
        ),
        migrations.AlterField(
            model_name='ubicacion852',
            name='signatura',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Signatura original ($h)'),
        ),
        migrations.CreateModel(
            name='Estanteria852',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estanteria', models.CharField(max_length=255, verbose_name='Estantería / Departamento ($c)')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estanterias', to='catalogacion.ubicacion852')),
            ],
        ),
    ]
