# Generated by Django 5.2.7 on 2025-11-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0018_tituloalternativo_texto_visualizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obrageneral',
            name='mencion_responsabilidad',
            field=models.TextField(blank=True, help_text='245 $c — Nombres en fuente', null=True),
        ),
    ]
