# Generated by Django 5.1.2 on 2025-11-05 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0018_alter_disponible856_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estanteria852',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='estanteria852',
            name='obra',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='estanterias_852', to='catalogacion.obrageneral'),
            preserve_default=False,
        ),
    ]
