# Generated by Django 5.1.2 on 2025-11-05 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0019_remove_estanteria852_ubicacion_estanteria852_obra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estanteria852',
            name='obra',
        ),
        migrations.AddField(
            model_name='estanteria852',
            name='ubicacion',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='estanterias_852', to='catalogacion.ubicacion852'),
            preserve_default=False,
        ),
    ]
