# Generated by Django 5.2.7 on 2025-11-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0019_alter_obrageneral_mencion_responsabilidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obrageneral',
            name='solista',
        ),
        migrations.AddField(
            model_name='mediointerpretacion382',
            name='solista',
            field=models.CharField(blank=True, help_text='382 $b — Solista', max_length=100, null=True),
        ),
    ]
