# Generated by Django 5.1.2 on 2025-11-05 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0020_remove_estanteria852_obra_estanteria852_ubicacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disponible856',
            options={'verbose_name': '856 - Disponible', 'verbose_name_plural': '🌐 856 - Recursos disponibles'},
        ),
        migrations.AlterModelOptions(
            name='estanteria852',
            options={'verbose_name': '852 $c – Estantería', 'verbose_name_plural': '📚 852 $c – Estanterías'},
        ),
        migrations.AlterModelOptions(
            name='ubicacion852',
            options={'verbose_name': '852 - Ubicación', 'verbose_name_plural': '📍 852 - Ubicaciones'},
        ),
        migrations.RemoveField(
            model_name='ubicacion852',
            name='institucion',
        ),
        migrations.RemoveField(
            model_name='ubicacion852',
            name='signatura',
        ),
        migrations.AddField(
            model_name='ubicacion852',
            name='institucion_persona',
            field=models.CharField(default='', help_text='852 $a – Institución o persona (no repetible)', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ubicacion852',
            name='signatura_original',
            field=models.CharField(blank=True, help_text='852 $h – Signatura original (no repetible)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='disponible856',
            name='texto_enlace',
            field=models.CharField(blank=True, help_text='856 $y – Texto del enlace (repetible)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='disponible856',
            name='url',
            field=models.URLField(help_text='856 $u – URL del recurso disponible', max_length=500),
        ),
        migrations.AlterField(
            model_name='estanteria852',
            name='estanteria',
            field=models.CharField(help_text='852 $c – Estantería (repetible)', max_length=255),
        ),
        migrations.AlterField(
            model_name='estanteria852',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estanterias', to='catalogacion.ubicacion852'),
        ),
    ]
