# Generated by Django 5.2.7 on 2025-11-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0020_remove_obrageneral_solista_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relacion700',
            name='nombre_700',
        ),
        migrations.RemoveField(
            model_name='nombrerelacionado700',
            name='fechas',
        ),
        migrations.AddField(
            model_name='nombrerelacionado700',
            name='autoria',
            field=models.CharField(blank=True, choices=[('atribuida', 'Atribuida'), ('certificada', 'Certificada'), ('erronea', 'Errónea')], help_text='700 $j – Calificador de atribución (NR)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='nombrerelacionado700',
            name='coordenadas_biograficas',
            field=models.CharField(blank=True, help_text='700 $d – Coordenadas biográficas (NR)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='nombrerelacionado700',
            name='relacion',
            field=models.CharField(blank=True, help_text='700 $i – Información sobre la relación (NR)', max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Autoria700',
        ),
        migrations.DeleteModel(
            name='Relacion700',
        ),
    ]
