# Generated by Django 5.2.7 on 2025-11-18 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0021_remove_relacion700_nombre_700_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borradorobra',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('convertido', 'Convertido a Obra'), ('descartado', 'Descartado')], default='activo', help_text='Estado del borrador: activo (en progreso), convertido (publicado como obra), descartado (eliminado por usuario)', max_length=20),
        ),
        migrations.AddField(
            model_name='borradorobra',
            name='obra_creada',
            field=models.ForeignKey(blank=True, help_text='Obra final creada a partir de este borrador', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrador_origen', to='catalogacion.obrageneral'),
        ),
        migrations.AddIndex(
            model_name='borradorobra',
            index=models.Index(fields=['estado'], name='catalogacio_estado_486460_idx'),
        ),
    ]
