# Generated by Django 5.1.2 on 2025-11-06 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0011_rename_codigo_idiomaobra_codigo_idioma_and_more'),
        ('catalogacion', '0021_alter_disponible856_options_and_more'),
    ]

    operations = [
    ]
