# Generated by Django 5.2.8 on 2025-11-09 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0022_merge_20251105_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='incipitmusical',
            name='armadura',
            field=models.CharField(blank=True, help_text='031 $n – Armadura', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='incipitmusical',
            name='clave',
            field=models.CharField(blank=True, help_text='031 $g – Clave musical (ej.: G-2, F-4)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='incipitmusical',
            name='nota_general',
            field=models.TextField(blank=True, help_text='031 $q – Nota general', null=True),
        ),
        migrations.AddField(
            model_name='incipitmusical',
            name='nota_validez_codificada',
            field=models.CharField(blank=True, help_text='031 $s – Nota de validez codificada', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='incipitmusical',
            name='personaje',
            field=models.CharField(blank=True, help_text='031 $e – Personaje', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='incipitmusical',
            name='tonalidad_modo',
            field=models.CharField(blank=True, help_text='031 $r – Tonalidad o modo (ej.: g, C mayor)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='incipitmusical',
            name='notacion_musical',
            field=models.TextField(blank=True, help_text='031 $p – Íncipit musical codificado en PAE (Plaine & Easie)', null=True),
        ),
    ]
