# Generated by Django 5.2.8 on 2025-11-13 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0023_incipitmusical_armadura_incipitmusical_clave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incipitmusical',
            name='tiempo',
            field=models.CharField(blank=True, help_text='031 $o – Tiempo', max_length=20, null=True),
        ),
    ]
