"""
Constantes y listas controladas para catalogación MARC21
Centralizadas para facilitar mantenimiento
"""

TONALIDADES = [
    ('Do mayor', 'Do mayor'),
    ('Do# mayor', 'Do# mayor'),
    ('Reb mayor', 'Re♭ mayor'),
    ('Re mayor', 'Re mayor'),
    ('Mib mayor', 'Mi♭ mayor'),
    ('Mi mayor', 'Mi mayor'),
    ('Fa mayor', 'Fa mayor'),
    ('Fa# mayor', 'Fa# mayor'),
    ('Sol mayor', 'Sol mayor'),
    ('Sol# mayor', 'Sol# mayor'),
    ('Lab mayor', 'La♭ mayor'),
    ('La mayor', 'La mayor'),
    ('Sib mayor', 'Si♭ mayor'),
    ('Si mayor', 'Si mayor'),
    ('Do menor', 'Do menor'),
    ('Do# menor', 'Do# menor'),
    ('Reb menor', 'Re♭ menor'),
    ('Re menor', 'Re menor'),
    ('Mib menor', 'Mi♭ menor'),
    ('Mi menor', 'Mi menor'),
    ('Fa menor', 'Fa menor'),
    ('Fa# menor', 'Fa# menor'),
    ('Sol menor', 'Sol menor'),
    ('Sol# menor', 'Sol# menor'),
    ('Lab menor', 'La♭ menor'),
    ('La menor', 'La menor'),
    ('Sib menor', 'Si♭ menor'),
    ('Si menor', 'Si menor'),
]

TECNICAS = [
    ('autógrafo', 'Autógrafo'),
    ('posible autógrafo', 'Posible autógrafo'),
    ('manuscrito', 'Manuscrito'),
    ('manuscrito digital', 'Manuscrito digital'),
    ('manuscrito de copista no identificado', 'Manuscrito de copista no identificado'),
    ('impreso', 'Impreso'),
    ('fotocopia de manuscrito', 'Fotocopia de manuscrito'),
    ('fotocopia de impreso', 'Fotocopia de impreso'),
]

FORMATOS = [
    ('parte', 'Parte'),
    ('partitura de piano', 'Partitura de piano'),
    ('partitura de coro', 'Partitura de coro'),
    ('partitura piano vocal', 'Partitura piano vocal'),
]

CODIGOS_LENGUAJE = [
    ('ger', 'Alemán'),
    ('spa', 'Español'),
    ('fre', 'Francés'),
    ('eng', 'Inglés'),
    ('ita', 'Italiano'),
    ('por', 'Portugués'),
]

CODIGOS_PAIS = [
    # ═══════════════════════════════════════════════════════════════
    # LATINOAMÉRICA Y EL CARIBE
    # ═══════════════════════════════════════════════════════════════
    ('ar', 'Argentina'),
    ('bf', 'Bahamas'),
    ('bb', 'Barbados'),
    ('bh', 'Belice'),
    ('bo', 'Bolivia'),
    ('br', 'Brasil'),
    ('cl', 'Chile'),
    ('co', 'Colombia'),
    ('cr', 'Costa Rica'),
    ('cu', 'Cuba'),
    ('dr', 'República Dominicana'),
    ('ec', 'Ecuador'),
    ('sv', 'El Salvador'),
    ('fg', 'Guayana Francesa'),
    ('gp', 'Guadalupe'),
    ('gt', 'Guatemala'),
    ('gy', 'Guyana'),
    ('ht', 'Haití'),
    ('ho', 'Honduras'),
    ('jm', 'Jamaica'),
    ('mq', 'Martinica'),
    ('mx', 'México'),
    ('na', 'Antillas Neerlandesas'),
    ('nq', 'Nicaragua'),
    ('pa', 'Panamá'),
    ('py', 'Paraguay'),
    ('pe', 'Perú'),
    ('pr', 'Puerto Rico'),
    ('sr', 'Surinam'),
    ('tg', 'Trinidad y Tobago'),
    ('uy', 'Uruguay'),
    ('ve', 'Venezuela'),
    ('vi', 'Islas Vírgenes'),
    # ═══════════════════════════════════════════════════════════════
    # AMÉRICA DEL NORTE
    # ═══════════════════════════════════════════════════════════════
    ('xxc', 'Canadá'),
    ('xxu', 'Estados Unidos'),
    # ═══════════════════════════════════════════════════════════════
    # EUROPA
    # ═══════════════════════════════════════════════════════════════
    ('aa', 'Albania'),
    ('an', 'Andorra'),
    ('au', 'Austria'),
    ('ba', 'Bosnia y Herzegovina'),
    ('be', 'Bélgica'),
    ('bu', 'Bulgaria'),
    ('bw', 'Bielorrusia'),
    ('ci', 'Croacia'),
    ('cy', 'Chipre'),
    ('xr', 'República Checa'),
    ('dk', 'Dinamarca'),
    ('er', 'Estonia'),
    ('fi', 'Finlandia'),
    ('fr', 'Francia'),
    ('gw', 'Alemania'),
    ('gr', 'Grecia'),
    ('hu', 'Hungría'),
    ('ic', 'Islandia'),
    ('ie', 'Irlanda'),
    ('it', 'Italia'),
    ('lv', 'Letonia'),
    ('lh', 'Liechtenstein'),
    ('li', 'Lituania'),
    ('lu', 'Luxemburgo'),
    ('mk', 'Macedonia del Norte'),
    ('mm', 'Malta'),
    ('mv', 'Moldavia'),
    ('mc', 'Mónaco'),
    ('mo', 'Montenegro'),
    ('ne', 'Países Bajos'),
    ('no', 'Noruega'),
    ('pl', 'Polonia'),
    ('po', 'Portugal'),
    ('rm', 'Rumania'),
    ('ru', 'Rusia'),
    ('sm', 'San Marino'),
    ('rb', 'Serbia'),
    ('xo', 'Eslovaquia'),
    ('xv', 'Eslovenia'),
    ('sp', 'España'),
    ('sw', 'Suecia'),
    ('sz', 'Suiza'),
    ('tu', 'Turquía'),
    ('un', 'Ucrania'),
    ('enk', 'Reino Unido'),
    ('vc', 'Ciudad del Vaticano'),
    # ═══════════════════════════════════════════════════════════════
    # ASIA
    # ═══════════════════════════════════════════════════════════════
    ('af', 'Afganistán'),
    ('ai', 'Armenia'),
    ('aj', 'Azerbaiyán'),
    ('bg', 'Bangladés'),
    ('bt', 'Bután'),
    ('bx', 'Brunéi'),
    ('cb', 'Camboya'),
    ('cc', 'China'),
    ('gs', 'Georgia'),
    ('ii', 'India'),
    ('io', 'Indonesia'),
    ('ir', 'Irán'),
    ('iq', 'Irak'),
    ('is', 'Israel'),
    ('ja', 'Japón'),
    ('jo', 'Jordania'),
    ('kz', 'Kazajistán'),
    ('kn', 'Corea del Norte'),
    ('ko', 'Corea del Sur'),
    ('ku', 'Kuwait'),
    ('kg', 'Kirguistán'),
    ('ls', 'Laos'),
    ('le', 'Líbano'),
    ('my', 'Malasia'),
    ('xc', 'Maldivas'),
    ('mp', 'Mongolia'),
    ('bm', 'Myanmar'),
    ('np', 'Nepal'),
    ('pk', 'Pakistán'),
    ('ph', 'Filipinas'),
    ('qa', 'Catar'),
    ('su', 'Arabia Saudita'),
    ('si', 'Singapur'),
    ('ce', 'Sri Lanka'),
    ('sy', 'Siria'),
    ('ta', 'Tayikistán'),
    ('th', 'Tailandia'),
    ('ti', 'Timor Oriental'),
    ('tk', 'Turkmenistán'),
    ('ts', 'Emiratos Árabes Unidos'),
    ('uz', 'Uzbekistán'),
    ('vm', 'Vietnam'),
    ('ye', 'Yemen'),
]

FUNCIONES_PERSONA = [
    ('arreglista', 'Arreglista'),
    ('coeditor', 'Coeditor'),
    ('compilador', 'Compilador'),
    ('compositor', 'Compositor'),
    ('copista', 'Copista'),
    ('dedicatario', 'Dedicatario'),
    ('editor', 'Editor'),
    ('prologuista', 'Prologuista'),
]

AUTORIAS_CHOICES = [
    ('atribuida', 'Atribuida'),
    ('certificada', 'Certificada'),
    ('erronea', 'Errónea'),
]

FUNCIONES_ENTIDAD = [
    ('coeditor', 'Coeditor'),
    ('dedicatario', 'Dedicatario'),
    ('editor', 'Editor'),
    ('lugar_ejecucion', 'Lugar de ejecución'),
    ('lugar_estreno', 'Lugar de estreno'),
    ('patrocinante', 'Patrocinante'),
]

MEDIOS_INTERPRETACION = [
    ('piano', 'Piano'),
    ('dos pianos', 'Dos pianos'),
    ('piano a cuatro manos', 'Piano a cuatro manos'),
    ('piano con acompañamiento', 'Piano con acompañamiento'),
]

# Mapeo de tipo_registro + nivel_bibliografico a tipo_obra
TIPO_OBRA_MAP = {
    ('d', 'c'): ('CM', 'Colección manuscrita'),
    ('d', 'a'): ('OICM', 'Obra en colección manuscrita'),
    ('d', 'm'): ('OIM', 'Obra manuscrita independiente'),
    ('c', 'c'): ('CI', 'Colección impresa'),
    ('c', 'a'): ('OICI', 'Obra en colección impresa'),
    ('c', 'm'): ('OII', 'Obra impresa independiente'),
}